// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin_extras.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAllElderCareSubs = `-- name: CountAllElderCareSubs :one
SELECT COUNT(*) FROM elder_care_subscriptions
`

func (q *Queries) CountAllElderCareSubs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllElderCareSubs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllSubscriptions = `-- name: CountAllSubscriptions :one
SELECT COUNT(*) FROM subscriptions
`

func (q *Queries) CountAllSubscriptions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllSubscriptions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllTriage = `-- name: CountAllTriage :one
SELECT COUNT(*) FROM triage
`

func (q *Queries) CountAllTriage(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllTriage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingTriage = `-- name: CountPendingTriage :one
SELECT COUNT(*) FROM triage WHERE status IN ('PENDING', 'REVIEWING')
`

func (q *Queries) CountPendingTriage(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingTriage)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQRToken = `-- name: CreateQRToken :one

INSERT INTO qr_tokens (merchant_id, amount, description, status, expires_at)
VALUES ($1, $2, $3, 'PENDING', NOW() + INTERVAL '10 minutes')
RETURNING id, token, merchant_id, amount, description, status, transaction_id, created_at, updated_at, expires_at
`

type CreateQRTokenParams struct {
	MerchantID  pgtype.UUID    `json:"merchant_id"`
	Amount      pgtype.Numeric `json:"amount"`
	Description pgtype.Text    `json:"description"`
}

// ════════════════════════════════════════════════════════════
// Merchant: QR tokens
// ════════════════════════════════════════════════════════════
func (q *Queries) CreateQRToken(ctx context.Context, arg CreateQRTokenParams) (QrToken, error) {
	row := q.db.QueryRow(ctx, createQRToken, arg.MerchantID, arg.Amount, arg.Description)
	var i QrToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.MerchantID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getQRToken = `-- name: GetQRToken :one
SELECT id, token, merchant_id, amount, description, status, transaction_id, created_at, updated_at, expires_at FROM qr_tokens WHERE token = $1
`

func (q *Queries) GetQRToken(ctx context.Context, token string) (QrToken, error) {
	row := q.db.QueryRow(ctx, getQRToken, token)
	var i QrToken
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.MerchantID,
		&i.Amount,
		&i.Description,
		&i.Status,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAllElderCareSubs = `-- name: ListAllElderCareSubs :many

SELECT
    e.id, e.user_id, e.merchant_id, e.credit_line_id, e.service_type,
    e.monthly_amount, e.status, e.next_billing_date, e.created_at, e.updated_at,
    u.full_name AS user_name,
    m.trade_name AS merchant_name
FROM elder_care_subscriptions e
JOIN users u ON e.user_id = u.id
LEFT JOIN merchants m ON e.merchant_id = m.id
ORDER BY e.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllElderCareSubsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllElderCareSubsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	ServiceType     string             `json:"service_type"`
	MonthlyAmount   pgtype.Numeric     `json:"monthly_amount"`
	Status          string             `json:"status"`
	NextBillingDate pgtype.Timestamptz `json:"next_billing_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UserName        string             `json:"user_name"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
}

// ════════════════════════════════════════════════════════════
// Admin: All elder care subscriptions
// ════════════════════════════════════════════════════════════
func (q *Queries) ListAllElderCareSubs(ctx context.Context, arg ListAllElderCareSubsParams) ([]ListAllElderCareSubsRow, error) {
	rows, err := q.db.Query(ctx, listAllElderCareSubs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllElderCareSubsRow
	for rows.Next() {
		var i ListAllElderCareSubsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.CreditLineID,
			&i.ServiceType,
			&i.MonthlyAmount,
			&i.Status,
			&i.NextBillingDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSubscriptions = `-- name: ListAllSubscriptions :many

SELECT
    s.id, s.user_id, s.merchant_id, s.credit_line_id, s.amount,
    s.product_name, s.status, s.next_billing_date, s.created_at, s.updated_at,
    u.full_name AS user_name,
    m.trade_name AS merchant_name
FROM subscriptions s
JOIN users u ON s.user_id = u.id
LEFT JOIN merchants m ON s.merchant_id = m.id
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllSubscriptionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllSubscriptionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	ProductName     string             `json:"product_name"`
	Status          string             `json:"status"`
	NextBillingDate pgtype.Timestamptz `json:"next_billing_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UserName        string             `json:"user_name"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
}

// ════════════════════════════════════════════════════════════
// Admin: All subscriptions
// ════════════════════════════════════════════════════════════
func (q *Queries) ListAllSubscriptions(ctx context.Context, arg ListAllSubscriptionsParams) ([]ListAllSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, listAllSubscriptions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllSubscriptionsRow
	for rows.Next() {
		var i ListAllSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.CreditLineID,
			&i.Amount,
			&i.ProductName,
			&i.Status,
			&i.NextBillingDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTriage = `-- name: ListAllTriage :many
SELECT t.id, t.user_id, t.symptoms, t.perceived_severity, t.priority, t.status, t.recommendation, t.created_at, t.updated_at, u.full_name AS user_name
FROM triage t
JOIN users u ON t.user_id = u.id
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllTriageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllTriageRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Symptoms          string             `json:"symptoms"`
	PerceivedSeverity int16              `json:"perceived_severity"`
	Priority          string             `json:"priority"`
	Status            string             `json:"status"`
	Recommendation    pgtype.Text        `json:"recommendation"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UserName          string             `json:"user_name"`
}

func (q *Queries) ListAllTriage(ctx context.Context, arg ListAllTriageParams) ([]ListAllTriageRow, error) {
	rows, err := q.db.Query(ctx, listAllTriage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTriageRow
	for rows.Next() {
		var i ListAllTriageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symptoms,
			&i.PerceivedSeverity,
			&i.Priority,
			&i.Status,
			&i.Recommendation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listElderCareSubsByMerchant = `-- name: ListElderCareSubsByMerchant :many

SELECT
    e.id, e.user_id, e.merchant_id, e.credit_line_id, e.service_type,
    e.monthly_amount, e.status, e.next_billing_date, e.created_at, e.updated_at,
    u.full_name AS user_name
FROM elder_care_subscriptions e
JOIN users u ON e.user_id = u.id
WHERE e.merchant_id = $1
ORDER BY e.created_at DESC
`

type ListElderCareSubsByMerchantRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	ServiceType     string             `json:"service_type"`
	MonthlyAmount   pgtype.Numeric     `json:"monthly_amount"`
	Status          string             `json:"status"`
	NextBillingDate pgtype.Timestamptz `json:"next_billing_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UserName        string             `json:"user_name"`
}

// ════════════════════════════════════════════════════════════
// Merchant: Elder care subscriptions for this merchant
// ════════════════════════════════════════════════════════════
func (q *Queries) ListElderCareSubsByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]ListElderCareSubsByMerchantRow, error) {
	rows, err := q.db.Query(ctx, listElderCareSubsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListElderCareSubsByMerchantRow
	for rows.Next() {
		var i ListElderCareSubsByMerchantRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.CreditLineID,
			&i.ServiceType,
			&i.MonthlyAmount,
			&i.Status,
			&i.NextBillingDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMerchantTransactionsToday = `-- name: ListMerchantTransactionsToday :many
SELECT t.id, t.user_id, t.merchant_id, t.credit_line_id, t.total_amount, t.down_payment, t.financed_amount, t.num_installments, t.status, t.qr_code_token, t.qr_expires_at, t.mdr_fee, t.description, t.created_at, t.updated_at, u.full_name AS user_name
FROM transactions t
JOIN users u ON t.user_id = u.id
WHERE t.merchant_id = $1 AND DATE(t.created_at) = CURRENT_DATE
ORDER BY t.created_at DESC
`

type ListMerchantTransactionsTodayRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	DownPayment     pgtype.Numeric     `json:"down_payment"`
	FinancedAmount  pgtype.Numeric     `json:"financed_amount"`
	NumInstallments int16              `json:"num_installments"`
	Status          string             `json:"status"`
	QrCodeToken     pgtype.Text        `json:"qr_code_token"`
	QrExpiresAt     pgtype.Timestamptz `json:"qr_expires_at"`
	MdrFee          pgtype.Numeric     `json:"mdr_fee"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UserName        string             `json:"user_name"`
}

func (q *Queries) ListMerchantTransactionsToday(ctx context.Context, merchantID pgtype.UUID) ([]ListMerchantTransactionsTodayRow, error) {
	rows, err := q.db.Query(ctx, listMerchantTransactionsToday, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMerchantTransactionsTodayRow
	for rows.Next() {
		var i ListMerchantTransactionsTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.CreditLineID,
			&i.TotalAmount,
			&i.DownPayment,
			&i.FinancedAmount,
			&i.NumInstallments,
			&i.Status,
			&i.QrCodeToken,
			&i.QrExpiresAt,
			&i.MdrFee,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTriage = `-- name: ListPendingTriage :many

SELECT t.id, t.user_id, t.symptoms, t.perceived_severity, t.priority, t.status, t.recommendation, t.created_at, t.updated_at, u.full_name AS user_name, u.phone AS user_phone
FROM triage t
JOIN users u ON t.user_id = u.id
WHERE t.status IN ('PENDING', 'REVIEWING')
ORDER BY
    CASE t.priority
        WHEN 'EMERGENCY' THEN 0
        WHEN 'HIGH' THEN 1
        WHEN 'MEDIUM' THEN 2
        WHEN 'LOW' THEN 3
    END,
    t.created_at DESC
LIMIT $1 OFFSET $2
`

type ListPendingTriageParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListPendingTriageRow struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Symptoms          string             `json:"symptoms"`
	PerceivedSeverity int16              `json:"perceived_severity"`
	Priority          string             `json:"priority"`
	Status            string             `json:"status"`
	Recommendation    pgtype.Text        `json:"recommendation"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	UserName          string             `json:"user_name"`
	UserPhone         string             `json:"user_phone"`
}

// ════════════════════════════════════════════════════════════
// Admin: Triage management
// ════════════════════════════════════════════════════════════
func (q *Queries) ListPendingTriage(ctx context.Context, arg ListPendingTriageParams) ([]ListPendingTriageRow, error) {
	rows, err := q.db.Query(ctx, listPendingTriage, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingTriageRow
	for rows.Next() {
		var i ListPendingTriageRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symptoms,
			&i.PerceivedSeverity,
			&i.Priority,
			&i.Status,
			&i.Recommendation,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const respondTriage = `-- name: RespondTriage :exec
UPDATE triage
SET status = $3, recommendation = $4
WHERE id = $1 AND id = $2
`

type RespondTriageParams struct {
	ID             pgtype.UUID `json:"id"`
	ID_2           pgtype.UUID `json:"id_2"`
	Status         string      `json:"status"`
	Recommendation pgtype.Text `json:"recommendation"`
}

func (q *Queries) RespondTriage(ctx context.Context, arg RespondTriageParams) error {
	_, err := q.db.Exec(ctx, respondTriage,
		arg.ID,
		arg.ID_2,
		arg.Status,
		arg.Recommendation,
	)
	return err
}

const updateQRTokenStatus = `-- name: UpdateQRTokenStatus :exec
UPDATE qr_tokens SET status = $2, updated_at = NOW() WHERE token = $1
`

type UpdateQRTokenStatusParams struct {
	Token  string `json:"token"`
	Status string `json:"status"`
}

func (q *Queries) UpdateQRTokenStatus(ctx context.Context, arg UpdateQRTokenStatusParams) error {
	_, err := q.db.Exec(ctx, updateQRTokenStatus, arg.Token, arg.Status)
	return err
}
