// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveMerchants = `-- name: CountActiveMerchants :one
SELECT COUNT(*) FROM merchants WHERE is_active = true
`

func (q *Queries) CountActiveMerchants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveMerchants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCreditLines = `-- name: CountCreditLines :one
SELECT COUNT(*) FROM credit_lines
`

func (q *Queries) CountCreditLines(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCreditLines)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMerchantTransactions = `-- name: CountMerchantTransactions :one
SELECT COUNT(*) FROM transactions WHERE merchant_id = $1
`

func (q *Queries) CountMerchantTransactions(ctx context.Context, merchantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMerchantTransactions, merchantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMerchants = `-- name: CountMerchants :one
SELECT COUNT(*) FROM merchants
`

func (q *Queries) CountMerchants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMerchants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOverdueInstallments = `-- name: CountOverdueInstallments :one
SELECT COUNT(*) FROM installments WHERE status = 'OVERDUE'
`

func (q *Queries) CountOverdueInstallments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOverdueInstallments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTransactions = `-- name: CountTransactions :one
SELECT COUNT(*) FROM transactions
`

func (q *Queries) CountTransactions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTransactions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedicalService = `-- name: CreateMedicalService :one
INSERT INTO medical_services (merchant_id, name, description, category, subcategory, price_usd, duration_min)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, name, description, category, subcategory, price_usd, duration_min, is_active, created_at, updated_at
`

type CreateMedicalServiceParams struct {
	MerchantID  pgtype.UUID    `json:"merchant_id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Category    string         `json:"category"`
	Subcategory pgtype.Text    `json:"subcategory"`
	PriceUsd    pgtype.Numeric `json:"price_usd"`
	DurationMin pgtype.Int2    `json:"duration_min"`
}

func (q *Queries) CreateMedicalService(ctx context.Context, arg CreateMedicalServiceParams) (MedicalService, error) {
	row := q.db.QueryRow(ctx, createMedicalService,
		arg.MerchantID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Subcategory,
		arg.PriceUsd,
		arg.DurationMin,
	)
	var i MedicalService
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Subcategory,
		&i.PriceUsd,
		&i.DurationMin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMedicalSupply = `-- name: CreateMedicalSupply :one
INSERT INTO medical_supplies (merchant_id, name, description, category, subcategory, price_usd, unit, stock, min_stock, requires_prescription)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, merchant_id, name, description, category, subcategory, price_usd, unit, stock, min_stock, requires_prescription, is_active, created_at, updated_at
`

type CreateMedicalSupplyParams struct {
	MerchantID           pgtype.UUID    `json:"merchant_id"`
	Name                 string         `json:"name"`
	Description          pgtype.Text    `json:"description"`
	Category             string         `json:"category"`
	Subcategory          pgtype.Text    `json:"subcategory"`
	PriceUsd             pgtype.Numeric `json:"price_usd"`
	Unit                 pgtype.Text    `json:"unit"`
	Stock                int32          `json:"stock"`
	MinStock             pgtype.Int4    `json:"min_stock"`
	RequiresPrescription bool           `json:"requires_prescription"`
}

func (q *Queries) CreateMedicalSupply(ctx context.Context, arg CreateMedicalSupplyParams) (MedicalSupply, error) {
	row := q.db.QueryRow(ctx, createMedicalSupply,
		arg.MerchantID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Subcategory,
		arg.PriceUsd,
		arg.Unit,
		arg.Stock,
		arg.MinStock,
		arg.RequiresPrescription,
	)
	var i MedicalSupply
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Subcategory,
		&i.PriceUsd,
		&i.Unit,
		&i.Stock,
		&i.MinStock,
		&i.RequiresPrescription,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMedicalService = `-- name: DeleteMedicalService :exec
DELETE FROM medical_services WHERE id = $1 AND merchant_id = $2
`

type DeleteMedicalServiceParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) DeleteMedicalService(ctx context.Context, arg DeleteMedicalServiceParams) error {
	_, err := q.db.Exec(ctx, deleteMedicalService, arg.ID, arg.MerchantID)
	return err
}

const deleteMedicalSupply = `-- name: DeleteMedicalSupply :exec
DELETE FROM medical_supplies WHERE id = $1 AND merchant_id = $2
`

type DeleteMedicalSupplyParams struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
}

func (q *Queries) DeleteMedicalSupply(ctx context.Context, arg DeleteMedicalSupplyParams) error {
	_, err := q.db.Exec(ctx, deleteMedicalSupply, arg.ID, arg.MerchantID)
	return err
}

const exportAllInstallments = `-- name: ExportAllInstallments :many
SELECT
  i.id, i.installment_num, i.amount, i.due_date, i.paid_at,
  i.status, i.reactivation_fee, i.days_overdue, i.created_at,
  u.full_name AS user_name, u.email AS user_email
FROM installments i
JOIN users u ON i.user_id = u.id
ORDER BY i.due_date DESC
LIMIT $1 OFFSET $2
`

type ExportAllInstallmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ExportAllInstallmentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	InstallmentNum  int16              `json:"installment_num"`
	Amount          pgtype.Numeric     `json:"amount"`
	DueDate         pgtype.Date        `json:"due_date"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	Status          string             `json:"status"`
	ReactivationFee pgtype.Numeric     `json:"reactivation_fee"`
	DaysOverdue     int32              `json:"days_overdue"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UserName        string             `json:"user_name"`
	UserEmail       pgtype.Text        `json:"user_email"`
}

func (q *Queries) ExportAllInstallments(ctx context.Context, arg ExportAllInstallmentsParams) ([]ExportAllInstallmentsRow, error) {
	rows, err := q.db.Query(ctx, exportAllInstallments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportAllInstallmentsRow
	for rows.Next() {
		var i ExportAllInstallmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.InstallmentNum,
			&i.Amount,
			&i.DueDate,
			&i.PaidAt,
			&i.Status,
			&i.ReactivationFee,
			&i.DaysOverdue,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportAllTransactions = `-- name: ExportAllTransactions :many
SELECT
  t.id, t.total_amount, t.down_payment, t.financed_amount,
  t.num_installments, t.status, t.mdr_fee, t.description, t.created_at,
  u.full_name AS user_name, u.email AS user_email,
  m.trade_name AS merchant_name, m.category AS merchant_category
FROM transactions t
JOIN users u ON t.user_id = u.id
JOIN merchants m ON t.merchant_id = m.id
ORDER BY t.created_at DESC
LIMIT $1 OFFSET $2
`

type ExportAllTransactionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ExportAllTransactionsRow struct {
	ID               pgtype.UUID        `json:"id"`
	TotalAmount      pgtype.Numeric     `json:"total_amount"`
	DownPayment      pgtype.Numeric     `json:"down_payment"`
	FinancedAmount   pgtype.Numeric     `json:"financed_amount"`
	NumInstallments  int16              `json:"num_installments"`
	Status           string             `json:"status"`
	MdrFee           pgtype.Numeric     `json:"mdr_fee"`
	Description      pgtype.Text        `json:"description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UserName         string             `json:"user_name"`
	UserEmail        pgtype.Text        `json:"user_email"`
	MerchantName     string             `json:"merchant_name"`
	MerchantCategory string             `json:"merchant_category"`
}

func (q *Queries) ExportAllTransactions(ctx context.Context, arg ExportAllTransactionsParams) ([]ExportAllTransactionsRow, error) {
	rows, err := q.db.Query(ctx, exportAllTransactions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportAllTransactionsRow
	for rows.Next() {
		var i ExportAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalAmount,
			&i.DownPayment,
			&i.FinancedAmount,
			&i.NumInstallments,
			&i.Status,
			&i.MdrFee,
			&i.Description,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.MerchantName,
			&i.MerchantCategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exportAllUsers = `-- name: ExportAllUsers :many

SELECT id, phone, email, full_name, national_id, role,
       level, points, total_paid, installments_paid_count, is_active,
       created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ExportAllUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ExportAllUsersRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Phone                 string             `json:"phone"`
	Email                 pgtype.Text        `json:"email"`
	FullName              string             `json:"full_name"`
	NationalID            pgtype.Text        `json:"national_id"`
	Role                  string             `json:"role"`
	Level                 int16              `json:"level"`
	Points                int32              `json:"points"`
	TotalPaid             pgtype.Numeric     `json:"total_paid"`
	InstallmentsPaidCount int32              `json:"installments_paid_count"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// ─── Export queries (paginated, for CSV) ────────────────────────────────────
func (q *Queries) ExportAllUsers(ctx context.Context, arg ExportAllUsersParams) ([]ExportAllUsersRow, error) {
	rows, err := q.db.Query(ctx, exportAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExportAllUsersRow
	for rows.Next() {
		var i ExportAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Email,
			&i.FullName,
			&i.NationalID,
			&i.Role,
			&i.Level,
			&i.Points,
			&i.TotalPaid,
			&i.InstallmentsPaidCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstallmentStatusBreakdown = `-- name: GetInstallmentStatusBreakdown :many
SELECT
  status,
  COUNT(*) AS count,
  COALESCE(SUM(amount), 0) AS total_amount
FROM installments
GROUP BY status
ORDER BY count DESC
`

type GetInstallmentStatusBreakdownRow struct {
	Status      string      `json:"status"`
	Count       int64       `json:"count"`
	TotalAmount interface{} `json:"total_amount"`
}

func (q *Queries) GetInstallmentStatusBreakdown(ctx context.Context) ([]GetInstallmentStatusBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getInstallmentStatusBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInstallmentStatusBreakdownRow
	for rows.Next() {
		var i GetInstallmentStatusBreakdownRow
		if err := rows.Scan(&i.Status, &i.Count, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantByUserID = `-- name: GetMerchantByUserID :one
SELECT m.id, m.legal_name, m.trade_name, m.rif, m.category, m.address, m.city, m.phone, m.email, m.contact_name, m.mdr_rate, m.bank_account_bs, m.bank_account_usd, m.is_active, m.is_online, m.min_transaction, m.created_at, m.updated_at, m.subcategory FROM merchants m
JOIN merchant_users mu ON m.id = mu.merchant_id
WHERE mu.user_id = $1
LIMIT 1
`

func (q *Queries) GetMerchantByUserID(ctx context.Context, userID pgtype.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByUserID, userID)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradeName,
		&i.Rif,
		&i.Category,
		&i.Address,
		&i.City,
		&i.Phone,
		&i.Email,
		&i.ContactName,
		&i.MdrRate,
		&i.BankAccountBs,
		&i.BankAccountUsd,
		&i.IsActive,
		&i.IsOnline,
		&i.MinTransaction,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subcategory,
	)
	return i, err
}

const getMerchantCategoryDistribution = `-- name: GetMerchantCategoryDistribution :many
SELECT
  category,
  COUNT(*) AS merchant_count
FROM merchants
WHERE is_active = true
GROUP BY category
ORDER BY merchant_count DESC
`

type GetMerchantCategoryDistributionRow struct {
	Category      string `json:"category"`
	MerchantCount int64  `json:"merchant_count"`
}

func (q *Queries) GetMerchantCategoryDistribution(ctx context.Context) ([]GetMerchantCategoryDistributionRow, error) {
	rows, err := q.db.Query(ctx, getMerchantCategoryDistribution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMerchantCategoryDistributionRow
	for rows.Next() {
		var i GetMerchantCategoryDistributionRow
		if err := rows.Scan(&i.Category, &i.MerchantCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantDashboardStats = `-- name: GetMerchantDashboardStats :one
SELECT
  COUNT(DISTINCT t.id) as total_transactions,
  COALESCE(SUM(t.total_amount), 0) as total_revenue,
  COUNT(DISTINCT t.user_id) as unique_customers,
  COALESCE(SUM(t.mdr_fee), 0) as total_mdr
FROM transactions t
WHERE t.merchant_id = $1 AND t.status != 'CANCELLED'
`

type GetMerchantDashboardStatsRow struct {
	TotalTransactions int64       `json:"total_transactions"`
	TotalRevenue      interface{} `json:"total_revenue"`
	UniqueCustomers   int64       `json:"unique_customers"`
	TotalMdr          interface{} `json:"total_mdr"`
}

func (q *Queries) GetMerchantDashboardStats(ctx context.Context, merchantID pgtype.UUID) (GetMerchantDashboardStatsRow, error) {
	row := q.db.QueryRow(ctx, getMerchantDashboardStats, merchantID)
	var i GetMerchantDashboardStatsRow
	err := row.Scan(
		&i.TotalTransactions,
		&i.TotalRevenue,
		&i.UniqueCustomers,
		&i.TotalMdr,
	)
	return i, err
}

const getMerchantPayoutsFiltered = `-- name: GetMerchantPayoutsFiltered :many
SELECT id, merchant_id, period_start, period_end, gross_amount, mdr_deducted, net_amount, status, paid_at, created_at FROM merchant_payouts
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetMerchantPayoutsFiltered(ctx context.Context, merchantID pgtype.UUID) ([]MerchantPayout, error) {
	rows, err := q.db.Query(ctx, getMerchantPayoutsFiltered, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MerchantPayout
	for rows.Next() {
		var i MerchantPayout
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.GrossAmount,
			&i.MdrDeducted,
			&i.NetAmount,
			&i.Status,
			&i.PaidAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMerchantTransactions = `-- name: GetMerchantTransactions :many
SELECT t.id, t.user_id, t.merchant_id, t.credit_line_id, t.total_amount, t.down_payment, t.financed_amount, t.num_installments, t.status, t.qr_code_token, t.qr_expires_at, t.mdr_fee, t.description, t.created_at, t.updated_at, u.full_name as user_name, u.phone as user_phone
FROM transactions t
JOIN users u ON t.user_id = u.id
WHERE t.merchant_id = $1
ORDER BY t.created_at DESC
LIMIT $2 OFFSET $3
`

type GetMerchantTransactionsParams struct {
	MerchantID pgtype.UUID `json:"merchant_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

type GetMerchantTransactionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	DownPayment     pgtype.Numeric     `json:"down_payment"`
	FinancedAmount  pgtype.Numeric     `json:"financed_amount"`
	NumInstallments int16              `json:"num_installments"`
	Status          string             `json:"status"`
	QrCodeToken     pgtype.Text        `json:"qr_code_token"`
	QrExpiresAt     pgtype.Timestamptz `json:"qr_expires_at"`
	MdrFee          pgtype.Numeric     `json:"mdr_fee"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	UserName        string             `json:"user_name"`
	UserPhone       string             `json:"user_phone"`
}

func (q *Queries) GetMerchantTransactions(ctx context.Context, arg GetMerchantTransactionsParams) ([]GetMerchantTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getMerchantTransactions, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMerchantTransactionsRow
	for rows.Next() {
		var i GetMerchantTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.CreditLineID,
			&i.TotalAmount,
			&i.DownPayment,
			&i.FinancedAmount,
			&i.NumInstallments,
			&i.Status,
			&i.QrCodeToken,
			&i.QrExpiresAt,
			&i.MdrFee,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByMonth = `-- name: GetRevenueByMonth :many

SELECT
  TO_CHAR(DATE_TRUNC('month', created_at), 'YYYY-MM') AS month,
  COALESCE(SUM(total_amount), 0) AS revenue,
  COUNT(*) AS transaction_count
FROM transactions
WHERE status != 'CANCELLED'
GROUP BY DATE_TRUNC('month', created_at)
ORDER BY month DESC
LIMIT 12
`

type GetRevenueByMonthRow struct {
	Month            string      `json:"month"`
	Revenue          interface{} `json:"revenue"`
	TransactionCount int64       `json:"transaction_count"`
}

// ─── Analytics queries ──────────────────────────────────────────────────────
func (q *Queries) GetRevenueByMonth(ctx context.Context) ([]GetRevenueByMonthRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByMonthRow
	for rows.Next() {
		var i GetRevenueByMonthRow
		if err := rows.Scan(&i.Month, &i.Revenue, &i.TransactionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopMerchantsByRevenue = `-- name: GetTopMerchantsByRevenue :many
SELECT
  m.trade_name AS merchant_name,
  m.category,
  COALESCE(SUM(t.total_amount), 0) AS revenue,
  COUNT(t.id) AS transaction_count
FROM merchants m
LEFT JOIN transactions t ON m.id = t.merchant_id AND t.status != 'CANCELLED'
GROUP BY m.id, m.trade_name, m.category
ORDER BY revenue DESC
LIMIT 5
`

type GetTopMerchantsByRevenueRow struct {
	MerchantName     string      `json:"merchant_name"`
	Category         string      `json:"category"`
	Revenue          interface{} `json:"revenue"`
	TransactionCount int64       `json:"transaction_count"`
}

func (q *Queries) GetTopMerchantsByRevenue(ctx context.Context) ([]GetTopMerchantsByRevenueRow, error) {
	rows, err := q.db.Query(ctx, getTopMerchantsByRevenue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopMerchantsByRevenueRow
	for rows.Next() {
		var i GetTopMerchantsByRevenueRow
		if err := rows.Scan(
			&i.MerchantName,
			&i.Category,
			&i.Revenue,
			&i.TransactionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionStatusBreakdown = `-- name: GetTransactionStatusBreakdown :many
SELECT
  status,
  COUNT(*) AS count,
  COALESCE(SUM(total_amount), 0) AS total_amount
FROM transactions
GROUP BY status
ORDER BY count DESC
`

type GetTransactionStatusBreakdownRow struct {
	Status      string      `json:"status"`
	Count       int64       `json:"count"`
	TotalAmount interface{} `json:"total_amount"`
}

func (q *Queries) GetTransactionStatusBreakdown(ctx context.Context) ([]GetTransactionStatusBreakdownRow, error) {
	rows, err := q.db.Query(ctx, getTransactionStatusBreakdown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTransactionStatusBreakdownRow
	for rows.Next() {
		var i GetTransactionStatusBreakdownRow
		if err := rows.Scan(&i.Status, &i.Count, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTriageConversion = `-- name: GetTriageConversion :one
SELECT
  COUNT(DISTINCT CASE WHEN status = 'PENDING' THEN id END) AS pending_count,
  COUNT(DISTINCT CASE WHEN status = 'REVIEWING' THEN id END) AS reviewing_count,
  COUNT(DISTINCT CASE WHEN status = 'RESOLVED' THEN id END) AS resolved_count,
  COUNT(DISTINCT CASE WHEN status = 'REFERRED' THEN id END) AS referred_count,
  COUNT(DISTINCT CASE WHEN status = 'COMPLETED' THEN id END) AS completed_count
FROM triage
`

type GetTriageConversionRow struct {
	PendingCount   int64 `json:"pending_count"`
	ReviewingCount int64 `json:"reviewing_count"`
	ResolvedCount  int64 `json:"resolved_count"`
	ReferredCount  int64 `json:"referred_count"`
	CompletedCount int64 `json:"completed_count"`
}

func (q *Queries) GetTriageConversion(ctx context.Context) (GetTriageConversionRow, error) {
	row := q.db.QueryRow(ctx, getTriageConversion)
	var i GetTriageConversionRow
	err := row.Scan(
		&i.PendingCount,
		&i.ReviewingCount,
		&i.ResolvedCount,
		&i.ReferredCount,
		&i.CompletedCount,
	)
	return i, err
}

const getUserByIDAdmin = `-- name: GetUserByIDAdmin :one
SELECT id, phone, email, full_name, national_id, role,
       level, points, total_paid, installments_paid_count, is_active,
       created_at, updated_at
FROM users WHERE id = $1
`

type GetUserByIDAdminRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Phone                 string             `json:"phone"`
	Email                 pgtype.Text        `json:"email"`
	FullName              string             `json:"full_name"`
	NationalID            pgtype.Text        `json:"national_id"`
	Role                  string             `json:"role"`
	Level                 int16              `json:"level"`
	Points                int32              `json:"points"`
	TotalPaid             pgtype.Numeric     `json:"total_paid"`
	InstallmentsPaidCount int32              `json:"installments_paid_count"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByIDAdmin(ctx context.Context, id pgtype.UUID) (GetUserByIDAdminRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDAdmin, id)
	var i GetUserByIDAdminRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FullName,
		&i.NationalID,
		&i.Role,
		&i.Level,
		&i.Points,
		&i.TotalPaid,
		&i.InstallmentsPaidCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllCreditLines = `-- name: ListAllCreditLines :many
SELECT cl.id, cl.user_id, cl.type, cl.limit_usd, cl.used_usd, cl.status, cl.paused_at, cl.reactivated_at, cl.created_at, cl.updated_at, cl.blocked_at, u.full_name as user_name, u.phone as user_phone
FROM credit_lines cl
JOIN users u ON cl.user_id = u.id
ORDER BY cl.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllCreditLinesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllCreditLinesRow struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Type          string             `json:"type"`
	LimitUsd      pgtype.Numeric     `json:"limit_usd"`
	UsedUsd       pgtype.Numeric     `json:"used_usd"`
	Status        string             `json:"status"`
	PausedAt      pgtype.Timestamptz `json:"paused_at"`
	ReactivatedAt pgtype.Timestamptz `json:"reactivated_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	BlockedAt     pgtype.Timestamptz `json:"blocked_at"`
	UserName      string             `json:"user_name"`
	UserPhone     string             `json:"user_phone"`
}

func (q *Queries) ListAllCreditLines(ctx context.Context, arg ListAllCreditLinesParams) ([]ListAllCreditLinesRow, error) {
	rows, err := q.db.Query(ctx, listAllCreditLines, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllCreditLinesRow
	for rows.Next() {
		var i ListAllCreditLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.LimitUsd,
			&i.UsedUsd,
			&i.Status,
			&i.PausedAt,
			&i.ReactivatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BlockedAt,
			&i.UserName,
			&i.UserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMerchants = `-- name: ListAllMerchants :many
SELECT id, legal_name, trade_name, rif, category, address, city, phone, email, contact_name, mdr_rate, bank_account_bs, bank_account_usd, is_active, is_online, min_transaction, created_at, updated_at, subcategory FROM merchants ORDER BY created_at DESC
`

func (q *Queries) ListAllMerchants(ctx context.Context) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, listAllMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Merchant
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.LegalName,
			&i.TradeName,
			&i.Rif,
			&i.Category,
			&i.Address,
			&i.City,
			&i.Phone,
			&i.Email,
			&i.ContactName,
			&i.MdrRate,
			&i.BankAccountBs,
			&i.BankAccountUsd,
			&i.IsActive,
			&i.IsOnline,
			&i.MinTransaction,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, phone, email, full_name, national_id, role,
       level, points, total_paid, installments_paid_count, is_active,
       created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID                    pgtype.UUID        `json:"id"`
	Phone                 string             `json:"phone"`
	Email                 pgtype.Text        `json:"email"`
	FullName              string             `json:"full_name"`
	NationalID            pgtype.Text        `json:"national_id"`
	Role                  string             `json:"role"`
	Level                 int16              `json:"level"`
	Points                int32              `json:"points"`
	TotalPaid             pgtype.Numeric     `json:"total_paid"`
	InstallmentsPaidCount int32              `json:"installments_paid_count"`
	IsActive              bool               `json:"is_active"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.Email,
			&i.FullName,
			&i.NationalID,
			&i.Role,
			&i.Level,
			&i.Points,
			&i.TotalPaid,
			&i.InstallmentsPaidCount,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumMerchantRevenue = `-- name: SumMerchantRevenue :one
SELECT COALESCE(SUM(total_amount), 0) FROM transactions
WHERE merchant_id = $1 AND status != 'CANCELLED'
`

func (q *Queries) SumMerchantRevenue(ctx context.Context, merchantID pgtype.UUID) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumMerchantRevenue, merchantID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const sumPendingInstallments = `-- name: SumPendingInstallments :one
SELECT COALESCE(SUM(amount), 0) FROM installments WHERE status IN ('PENDING', 'OVERDUE')
`

func (q *Queries) SumPendingInstallments(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumPendingInstallments)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const sumTotalTransactionAmount = `-- name: SumTotalTransactionAmount :one
SELECT COALESCE(SUM(total_amount), 0) FROM transactions WHERE status != 'CANCELLED'
`

func (q *Queries) SumTotalTransactionAmount(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRow(ctx, sumTotalTransactionAmount)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const updateCreditLineLimit = `-- name: UpdateCreditLineLimit :exec
UPDATE credit_lines SET limit_usd = $2 WHERE id = $1
`

type UpdateCreditLineLimitParams struct {
	ID       pgtype.UUID    `json:"id"`
	LimitUsd pgtype.Numeric `json:"limit_usd"`
}

func (q *Queries) UpdateCreditLineLimit(ctx context.Context, arg UpdateCreditLineLimitParams) error {
	_, err := q.db.Exec(ctx, updateCreditLineLimit, arg.ID, arg.LimitUsd)
	return err
}

const updateMedicalService = `-- name: UpdateMedicalService :exec
UPDATE medical_services
SET name = $2, description = $3, category = $4, subcategory = $5,
    price_usd = $6, duration_min = $7, is_active = $8
WHERE id = $1 AND merchant_id = $9
`

type UpdateMedicalServiceParams struct {
	ID          pgtype.UUID    `json:"id"`
	Name        string         `json:"name"`
	Description pgtype.Text    `json:"description"`
	Category    string         `json:"category"`
	Subcategory pgtype.Text    `json:"subcategory"`
	PriceUsd    pgtype.Numeric `json:"price_usd"`
	DurationMin pgtype.Int2    `json:"duration_min"`
	IsActive    bool           `json:"is_active"`
	MerchantID  pgtype.UUID    `json:"merchant_id"`
}

func (q *Queries) UpdateMedicalService(ctx context.Context, arg UpdateMedicalServiceParams) error {
	_, err := q.db.Exec(ctx, updateMedicalService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Subcategory,
		arg.PriceUsd,
		arg.DurationMin,
		arg.IsActive,
		arg.MerchantID,
	)
	return err
}

const updateMedicalSupply = `-- name: UpdateMedicalSupply :exec
UPDATE medical_supplies
SET name = $2, description = $3, category = $4, subcategory = $5,
    price_usd = $6, unit = $7, stock = $8, min_stock = $9,
    requires_prescription = $10, is_active = $11
WHERE id = $1 AND merchant_id = $12
`

type UpdateMedicalSupplyParams struct {
	ID                   pgtype.UUID    `json:"id"`
	Name                 string         `json:"name"`
	Description          pgtype.Text    `json:"description"`
	Category             string         `json:"category"`
	Subcategory          pgtype.Text    `json:"subcategory"`
	PriceUsd             pgtype.Numeric `json:"price_usd"`
	Unit                 pgtype.Text    `json:"unit"`
	Stock                int32          `json:"stock"`
	MinStock             pgtype.Int4    `json:"min_stock"`
	RequiresPrescription bool           `json:"requires_prescription"`
	IsActive             bool           `json:"is_active"`
	MerchantID           pgtype.UUID    `json:"merchant_id"`
}

func (q *Queries) UpdateMedicalSupply(ctx context.Context, arg UpdateMedicalSupplyParams) error {
	_, err := q.db.Exec(ctx, updateMedicalSupply,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Subcategory,
		arg.PriceUsd,
		arg.Unit,
		arg.Stock,
		arg.MinStock,
		arg.RequiresPrescription,
		arg.IsActive,
		arg.MerchantID,
	)
	return err
}

const updateMerchantStatus = `-- name: UpdateMerchantStatus :one
UPDATE merchants SET is_active = $2 WHERE id = $1
RETURNING id, legal_name, trade_name, is_active
`

type UpdateMerchantStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

type UpdateMerchantStatusRow struct {
	ID        pgtype.UUID `json:"id"`
	LegalName string      `json:"legal_name"`
	TradeName string      `json:"trade_name"`
	IsActive  bool        `json:"is_active"`
}

func (q *Queries) UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (UpdateMerchantStatusRow, error) {
	row := q.db.QueryRow(ctx, updateMerchantStatus, arg.ID, arg.IsActive)
	var i UpdateMerchantStatusRow
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradeName,
		&i.IsActive,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2 WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   pgtype.UUID `json:"id"`
	Role string      `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET is_active = $2 WHERE id = $1
RETURNING id, email, full_name, is_active
`

type UpdateUserStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
}

type UpdateUserStatusRow struct {
	ID       pgtype.UUID `json:"id"`
	Email    pgtype.Text `json:"email"`
	FullName string      `json:"full_name"`
	IsActive bool        `json:"is_active"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UpdateUserStatusRow, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.IsActive)
	var i UpdateUserStatusRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FullName,
		&i.IsActive,
	)
	return i, err
}
