// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_log (user_id, action, resource_id, ip_address, user_agent, created_at)
VALUES ($1, $2, $3, $4, $5, NOW())
`

type InsertAuditLogParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Action     string      `json:"action"`
	ResourceID pgtype.UUID `json:"resource_id"`
	IpAddress  pgtype.Text `json:"ip_address"`
	UserAgent  pgtype.Text `json:"user_agent"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.Action,
		arg.ResourceID,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}
