// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSubscriptionItem = `-- name: CreateSubscriptionItem :one
INSERT INTO subscription_items (subscription_id, supply_id, item_name, quantity, unit_price_usd)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, subscription_id, supply_id, item_name, quantity, unit_price_usd
`

type CreateSubscriptionItemParams struct {
	SubscriptionID pgtype.UUID    `json:"subscription_id"`
	SupplyID       pgtype.UUID    `json:"supply_id"`
	ItemName       string         `json:"item_name"`
	Quantity       int16          `json:"quantity"`
	UnitPriceUsd   pgtype.Numeric `json:"unit_price_usd"`
}

func (q *Queries) CreateSubscriptionItem(ctx context.Context, arg CreateSubscriptionItemParams) (SubscriptionItem, error) {
	row := q.db.QueryRow(ctx, createSubscriptionItem,
		arg.SubscriptionID,
		arg.SupplyID,
		arg.ItemName,
		arg.Quantity,
		arg.UnitPriceUsd,
	)
	var i SubscriptionItem
	err := row.Scan(
		&i.ID,
		&i.SubscriptionID,
		&i.SupplyID,
		&i.ItemName,
		&i.Quantity,
		&i.UnitPriceUsd,
	)
	return i, err
}

const createTransactionItem = `-- name: CreateTransactionItem :one
INSERT INTO transaction_items (transaction_id, service_id, supply_id, item_name, quantity, unit_price_usd)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, transaction_id, service_id, supply_id, item_name, quantity, unit_price_usd, created_at
`

type CreateTransactionItemParams struct {
	TransactionID pgtype.UUID    `json:"transaction_id"`
	ServiceID     pgtype.UUID    `json:"service_id"`
	SupplyID      pgtype.UUID    `json:"supply_id"`
	ItemName      string         `json:"item_name"`
	Quantity      int16          `json:"quantity"`
	UnitPriceUsd  pgtype.Numeric `json:"unit_price_usd"`
}

func (q *Queries) CreateTransactionItem(ctx context.Context, arg CreateTransactionItemParams) (TransactionItem, error) {
	row := q.db.QueryRow(ctx, createTransactionItem,
		arg.TransactionID,
		arg.ServiceID,
		arg.SupplyID,
		arg.ItemName,
		arg.Quantity,
		arg.UnitPriceUsd,
	)
	var i TransactionItem
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ServiceID,
		&i.SupplyID,
		&i.ItemName,
		&i.Quantity,
		&i.UnitPriceUsd,
		&i.CreatedAt,
	)
	return i, err
}

const decrementSupplyStock = `-- name: DecrementSupplyStock :exec
UPDATE medical_supplies SET stock = stock - $2 WHERE id = $1 AND stock >= $2
`

type DecrementSupplyStockParams struct {
	ID    pgtype.UUID `json:"id"`
	Stock int32       `json:"stock"`
}

func (q *Queries) DecrementSupplyStock(ctx context.Context, arg DecrementSupplyStockParams) error {
	_, err := q.db.Exec(ctx, decrementSupplyStock, arg.ID, arg.Stock)
	return err
}

const getMerchantsByCategory = `-- name: GetMerchantsByCategory :many
SELECT id, legal_name, trade_name, rif, category, address, city, phone, email, contact_name, mdr_rate, bank_account_bs, bank_account_usd, is_active, is_online, min_transaction, created_at, updated_at, subcategory FROM merchants
WHERE is_active = true AND ($1::text = '' OR category = $1)
ORDER BY trade_name
`

func (q *Queries) GetMerchantsByCategory(ctx context.Context, dollar_1 string) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, getMerchantsByCategory, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Merchant
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.LegalName,
			&i.TradeName,
			&i.Rif,
			&i.Category,
			&i.Address,
			&i.City,
			&i.Phone,
			&i.Email,
			&i.ContactName,
			&i.MdrRate,
			&i.BankAccountBs,
			&i.BankAccountUsd,
			&i.IsActive,
			&i.IsOnline,
			&i.MinTransaction,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subcategory,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, merchant_id, name, description, category, subcategory, price_usd, duration_min, is_active, created_at, updated_at FROM medical_services WHERE id = $1
`

func (q *Queries) GetServiceByID(ctx context.Context, id pgtype.UUID) (MedicalService, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i MedicalService
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Subcategory,
		&i.PriceUsd,
		&i.DurationMin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServicesByMerchant = `-- name: GetServicesByMerchant :many
SELECT id, merchant_id, name, description, category, subcategory, price_usd, duration_min, is_active, created_at, updated_at FROM medical_services
WHERE merchant_id = $1 AND is_active = true
ORDER BY category, name
`

func (q *Queries) GetServicesByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]MedicalService, error) {
	rows, err := q.db.Query(ctx, getServicesByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedicalService
	for rows.Next() {
		var i MedicalService
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Subcategory,
			&i.PriceUsd,
			&i.DurationMin,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionItems = `-- name: GetSubscriptionItems :many
SELECT id, subscription_id, supply_id, item_name, quantity, unit_price_usd FROM subscription_items WHERE subscription_id = $1
`

func (q *Queries) GetSubscriptionItems(ctx context.Context, subscriptionID pgtype.UUID) ([]SubscriptionItem, error) {
	rows, err := q.db.Query(ctx, getSubscriptionItems, subscriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubscriptionItem
	for rows.Next() {
		var i SubscriptionItem
		if err := rows.Scan(
			&i.ID,
			&i.SubscriptionID,
			&i.SupplyID,
			&i.ItemName,
			&i.Quantity,
			&i.UnitPriceUsd,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSuppliesByMerchant = `-- name: GetSuppliesByMerchant :many
SELECT id, merchant_id, name, description, category, subcategory, price_usd, unit, stock, min_stock, requires_prescription, is_active, created_at, updated_at FROM medical_supplies
WHERE merchant_id = $1 AND is_active = true
ORDER BY category, name
`

func (q *Queries) GetSuppliesByMerchant(ctx context.Context, merchantID pgtype.UUID) ([]MedicalSupply, error) {
	rows, err := q.db.Query(ctx, getSuppliesByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedicalSupply
	for rows.Next() {
		var i MedicalSupply
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Subcategory,
			&i.PriceUsd,
			&i.Unit,
			&i.Stock,
			&i.MinStock,
			&i.RequiresPrescription,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplyByID = `-- name: GetSupplyByID :one
SELECT id, merchant_id, name, description, category, subcategory, price_usd, unit, stock, min_stock, requires_prescription, is_active, created_at, updated_at FROM medical_supplies WHERE id = $1
`

func (q *Queries) GetSupplyByID(ctx context.Context, id pgtype.UUID) (MedicalSupply, error) {
	row := q.db.QueryRow(ctx, getSupplyByID, id)
	var i MedicalSupply
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Description,
		&i.Category,
		&i.Subcategory,
		&i.PriceUsd,
		&i.Unit,
		&i.Stock,
		&i.MinStock,
		&i.RequiresPrescription,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionItems = `-- name: GetTransactionItems :many
SELECT id, transaction_id, service_id, supply_id, item_name, quantity, unit_price_usd, created_at FROM transaction_items WHERE transaction_id = $1
`

func (q *Queries) GetTransactionItems(ctx context.Context, transactionID pgtype.UUID) ([]TransactionItem, error) {
	rows, err := q.db.Query(ctx, getTransactionItems, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TransactionItem
	for rows.Next() {
		var i TransactionItem
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.ServiceID,
			&i.SupplyID,
			&i.ItemName,
			&i.Quantity,
			&i.UnitPriceUsd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServices = `-- name: SearchServices :many
SELECT
    s.id, s.merchant_id, s.name, s.description, s.category, s.subcategory,
    s.price_usd, s.duration_min, s.is_active,
    m.trade_name AS merchant_name, m.city AS merchant_city
FROM medical_services s
JOIN merchants m ON s.merchant_id = m.id
WHERE s.is_active = true AND m.is_active = true
AND ($1::text = '' OR s.category = $1)
AND ($2::text = '' OR s.name ILIKE '%' || $2 || '%')
ORDER BY s.price_usd ASC
`

type SearchServicesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

type SearchServicesRow struct {
	ID           pgtype.UUID    `json:"id"`
	MerchantID   pgtype.UUID    `json:"merchant_id"`
	Name         string         `json:"name"`
	Description  pgtype.Text    `json:"description"`
	Category     string         `json:"category"`
	Subcategory  pgtype.Text    `json:"subcategory"`
	PriceUsd     pgtype.Numeric `json:"price_usd"`
	DurationMin  pgtype.Int2    `json:"duration_min"`
	IsActive     bool           `json:"is_active"`
	MerchantName string         `json:"merchant_name"`
	MerchantCity pgtype.Text    `json:"merchant_city"`
}

func (q *Queries) SearchServices(ctx context.Context, arg SearchServicesParams) ([]SearchServicesRow, error) {
	rows, err := q.db.Query(ctx, searchServices, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchServicesRow
	for rows.Next() {
		var i SearchServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Subcategory,
			&i.PriceUsd,
			&i.DurationMin,
			&i.IsActive,
			&i.MerchantName,
			&i.MerchantCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSupplies = `-- name: SearchSupplies :many
SELECT
    s.id, s.merchant_id, s.name, s.description, s.category, s.subcategory,
    s.price_usd, s.unit, s.stock, s.requires_prescription, s.is_active,
    m.trade_name AS merchant_name, m.city AS merchant_city
FROM medical_supplies s
JOIN merchants m ON s.merchant_id = m.id
WHERE s.is_active = true AND m.is_active = true
AND ($1::text = '' OR s.category = $1)
AND ($2::text = '' OR s.name ILIKE '%' || $2 || '%')
ORDER BY s.price_usd ASC
`

type SearchSuppliesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

type SearchSuppliesRow struct {
	ID                   pgtype.UUID    `json:"id"`
	MerchantID           pgtype.UUID    `json:"merchant_id"`
	Name                 string         `json:"name"`
	Description          pgtype.Text    `json:"description"`
	Category             string         `json:"category"`
	Subcategory          pgtype.Text    `json:"subcategory"`
	PriceUsd             pgtype.Numeric `json:"price_usd"`
	Unit                 pgtype.Text    `json:"unit"`
	Stock                int32          `json:"stock"`
	RequiresPrescription bool           `json:"requires_prescription"`
	IsActive             bool           `json:"is_active"`
	MerchantName         string         `json:"merchant_name"`
	MerchantCity         pgtype.Text    `json:"merchant_city"`
}

func (q *Queries) SearchSupplies(ctx context.Context, arg SearchSuppliesParams) ([]SearchSuppliesRow, error) {
	rows, err := q.db.Query(ctx, searchSupplies, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSuppliesRow
	for rows.Next() {
		var i SearchSuppliesRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Description,
			&i.Category,
			&i.Subcategory,
			&i.PriceUsd,
			&i.Unit,
			&i.Stock,
			&i.RequiresPrescription,
			&i.IsActive,
			&i.MerchantName,
			&i.MerchantCity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
