// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credit.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstallment = `-- name: CreateInstallment :one
INSERT INTO installments (
    transaction_id, user_id, installment_num, amount, due_date
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, transaction_id, user_id, installment_num, amount, due_date, paid_at, status, reactivation_fee, days_overdue, created_at, updated_at
`

type CreateInstallmentParams struct {
	TransactionID  pgtype.UUID    `json:"transaction_id"`
	UserID         pgtype.UUID    `json:"user_id"`
	InstallmentNum int16          `json:"installment_num"`
	Amount         pgtype.Numeric `json:"amount"`
	DueDate        pgtype.Date    `json:"due_date"`
}

func (q *Queries) CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (Installment, error) {
	row := q.db.QueryRow(ctx, createInstallment,
		arg.TransactionID,
		arg.UserID,
		arg.InstallmentNum,
		arg.Amount,
		arg.DueDate,
	)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.UserID,
		&i.InstallmentNum,
		&i.Amount,
		&i.DueDate,
		&i.PaidAt,
		&i.Status,
		&i.ReactivationFee,
		&i.DaysOverdue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id, merchant_id, credit_line_id, total_amount, down_payment, financed_amount, num_installments, qr_code_token, mdr_fee, description
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, user_id, merchant_id, credit_line_id, total_amount, down_payment, financed_amount, num_installments, status, qr_code_token, qr_expires_at, mdr_fee, description, created_at, updated_at
`

type CreateTransactionParams struct {
	UserID          pgtype.UUID    `json:"user_id"`
	MerchantID      pgtype.UUID    `json:"merchant_id"`
	CreditLineID    pgtype.UUID    `json:"credit_line_id"`
	TotalAmount     pgtype.Numeric `json:"total_amount"`
	DownPayment     pgtype.Numeric `json:"down_payment"`
	FinancedAmount  pgtype.Numeric `json:"financed_amount"`
	NumInstallments int16          `json:"num_installments"`
	QrCodeToken     pgtype.Text    `json:"qr_code_token"`
	MdrFee          pgtype.Numeric `json:"mdr_fee"`
	Description     pgtype.Text    `json:"description"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.MerchantID,
		arg.CreditLineID,
		arg.TotalAmount,
		arg.DownPayment,
		arg.FinancedAmount,
		arg.NumInstallments,
		arg.QrCodeToken,
		arg.MdrFee,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.CreditLineID,
		&i.TotalAmount,
		&i.DownPayment,
		&i.FinancedAmount,
		&i.NumInstallments,
		&i.Status,
		&i.QrCodeToken,
		&i.QrExpiresAt,
		&i.MdrFee,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCreditLineByUser = `-- name: GetCreditLineByUser :one
SELECT id, user_id, type, limit_usd, used_usd, status, paused_at, reactivated_at, created_at, updated_at FROM credit_lines 
WHERE user_id = $1 AND type = $2
`

type GetCreditLineByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Type   string      `json:"type"`
}

func (q *Queries) GetCreditLineByUser(ctx context.Context, arg GetCreditLineByUserParams) (CreditLine, error) {
	row := q.db.QueryRow(ctx, getCreditLineByUser, arg.UserID, arg.Type)
	var i CreditLine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.LimitUsd,
		&i.UsedUsd,
		&i.Status,
		&i.PausedAt,
		&i.ReactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCreditLineUsage = `-- name: UpdateCreditLineUsage :one
UPDATE credit_lines
SET 
    used_usd = used_usd + $3,
    status = $4
WHERE user_id = $1 AND type = $2
RETURNING id, user_id, type, limit_usd, used_usd, status, paused_at, reactivated_at, created_at, updated_at
`

type UpdateCreditLineUsageParams struct {
	UserID  pgtype.UUID    `json:"user_id"`
	Type    string         `json:"type"`
	UsedUsd pgtype.Numeric `json:"used_usd"`
	Status  string         `json:"status"`
}

func (q *Queries) UpdateCreditLineUsage(ctx context.Context, arg UpdateCreditLineUsageParams) (CreditLine, error) {
	row := q.db.QueryRow(ctx, updateCreditLineUsage,
		arg.UserID,
		arg.Type,
		arg.UsedUsd,
		arg.Status,
	)
	var i CreditLine
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.LimitUsd,
		&i.UsedUsd,
		&i.Status,
		&i.PausedAt,
		&i.ReactivatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
