// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelAppointment = `-- name: CancelAppointment :exec
UPDATE appointments SET status = 'CANCELLED'
WHERE id = $1 AND user_id = $2
`

type CancelAppointmentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CancelAppointment(ctx context.Context, arg CancelAppointmentParams) error {
	_, err := q.db.Exec(ctx, cancelAppointment, arg.ID, arg.UserID)
	return err
}

const checkAppointmentConflict = `-- name: CheckAppointmentConflict :one
SELECT id FROM appointments
WHERE merchant_id = $1
  AND appointment_date = $2
  AND appointment_time = $3
  AND status NOT IN ('CANCELLED', 'COMPLETED')
LIMIT 1
`

type CheckAppointmentConflictParams struct {
	MerchantID      pgtype.UUID `json:"merchant_id"`
	AppointmentDate pgtype.Date `json:"appointment_date"`
	AppointmentTime pgtype.Time `json:"appointment_time"`
}

func (q *Queries) CheckAppointmentConflict(ctx context.Context, arg CheckAppointmentConflictParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkAppointmentConflict, arg.MerchantID, arg.AppointmentDate, arg.AppointmentTime)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const countAppointments = `-- name: CountAppointments :one
SELECT COUNT(*) FROM appointments WHERE user_id = $1
`

func (q *Queries) CountAppointments(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAppointments, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMedicalRecords = `-- name: CountMedicalRecords :one
SELECT COUNT(*) FROM medical_records WHERE user_id = $1
`

func (q *Queries) CountMedicalRecords(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMedicalRecords, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (
    user_id, merchant_id, service_id,
    appointment_date, appointment_time, duration_min, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, merchant_id, service_id, appointment_date, appointment_time, duration_min, status, notes, created_at, updated_at
`

type CreateAppointmentParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	MerchantID      pgtype.UUID `json:"merchant_id"`
	ServiceID       pgtype.UUID `json:"service_id"`
	AppointmentDate pgtype.Date `json:"appointment_date"`
	AppointmentTime pgtype.Time `json:"appointment_time"`
	DurationMin     int16       `json:"duration_min"`
	Notes           pgtype.Text `json:"notes"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.UserID,
		arg.MerchantID,
		arg.ServiceID,
		arg.AppointmentDate,
		arg.AppointmentTime,
		arg.DurationMin,
		arg.Notes,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.ServiceID,
		&i.AppointmentDate,
		&i.AppointmentTime,
		&i.DurationMin,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFamilyMember = `-- name: CreateFamilyMember :one
INSERT INTO family_members (caregiver_id, patient_id, relation, permissions)
VALUES ($1, $2, $3, $4)
RETURNING id, caregiver_id, patient_id, relation, status, permissions, created_at, updated_at
`

type CreateFamilyMemberParams struct {
	CaregiverID pgtype.UUID `json:"caregiver_id"`
	PatientID   pgtype.UUID `json:"patient_id"`
	Relation    pgtype.Text `json:"relation"`
	Permissions []string    `json:"permissions"`
}

func (q *Queries) CreateFamilyMember(ctx context.Context, arg CreateFamilyMemberParams) (FamilyMember, error) {
	row := q.db.QueryRow(ctx, createFamilyMember,
		arg.CaregiverID,
		arg.PatientID,
		arg.Relation,
		arg.Permissions,
	)
	var i FamilyMember
	err := row.Scan(
		&i.ID,
		&i.CaregiverID,
		&i.PatientID,
		&i.Relation,
		&i.Status,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHealthProfile = `-- name: CreateHealthProfile :one
INSERT INTO health_profiles (
    user_id, blood_type, height_cm, weight_kg,
    allergies, chronic_conditions, current_medications,
    emergency_contact_name, emergency_contact_phone, emergency_contact_relation, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, user_id, blood_type, height_cm, weight_kg, allergies, chronic_conditions, current_medications, emergency_contact_name, emergency_contact_phone, emergency_contact_relation, notes, created_at, updated_at
`

type CreateHealthProfileParams struct {
	UserID                   pgtype.UUID    `json:"user_id"`
	BloodType                pgtype.Text    `json:"blood_type"`
	HeightCm                 pgtype.Int2    `json:"height_cm"`
	WeightKg                 pgtype.Numeric `json:"weight_kg"`
	Allergies                []string       `json:"allergies"`
	ChronicConditions        []string       `json:"chronic_conditions"`
	CurrentMedications       []string       `json:"current_medications"`
	EmergencyContactName     pgtype.Text    `json:"emergency_contact_name"`
	EmergencyContactPhone    pgtype.Text    `json:"emergency_contact_phone"`
	EmergencyContactRelation pgtype.Text    `json:"emergency_contact_relation"`
	Notes                    pgtype.Text    `json:"notes"`
}

func (q *Queries) CreateHealthProfile(ctx context.Context, arg CreateHealthProfileParams) (HealthProfile, error) {
	row := q.db.QueryRow(ctx, createHealthProfile,
		arg.UserID,
		arg.BloodType,
		arg.HeightCm,
		arg.WeightKg,
		arg.Allergies,
		arg.ChronicConditions,
		arg.CurrentMedications,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.EmergencyContactRelation,
		arg.Notes,
	)
	var i HealthProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BloodType,
		&i.HeightCm,
		&i.WeightKg,
		&i.Allergies,
		&i.ChronicConditions,
		&i.CurrentMedications,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.EmergencyContactRelation,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMedicalRecord = `-- name: CreateMedicalRecord :one
INSERT INTO medical_records (
    user_id, transaction_id, merchant_id, service_id,
    record_type, diagnosis, prescription, doctor_name, notes, record_date
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, transaction_id, merchant_id, service_id, record_type, diagnosis, prescription, doctor_name, notes, record_date, created_at, updated_at
`

type CreateMedicalRecordParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
	MerchantID    pgtype.UUID `json:"merchant_id"`
	ServiceID     pgtype.UUID `json:"service_id"`
	RecordType    string      `json:"record_type"`
	Diagnosis     pgtype.Text `json:"diagnosis"`
	Prescription  pgtype.Text `json:"prescription"`
	DoctorName    pgtype.Text `json:"doctor_name"`
	Notes         pgtype.Text `json:"notes"`
	RecordDate    pgtype.Date `json:"record_date"`
}

func (q *Queries) CreateMedicalRecord(ctx context.Context, arg CreateMedicalRecordParams) (MedicalRecord, error) {
	row := q.db.QueryRow(ctx, createMedicalRecord,
		arg.UserID,
		arg.TransactionID,
		arg.MerchantID,
		arg.ServiceID,
		arg.RecordType,
		arg.Diagnosis,
		arg.Prescription,
		arg.DoctorName,
		arg.Notes,
		arg.RecordDate,
	)
	var i MedicalRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.MerchantID,
		&i.ServiceID,
		&i.RecordType,
		&i.Diagnosis,
		&i.Prescription,
		&i.DoctorName,
		&i.Notes,
		&i.RecordDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMedicationReminder = `-- name: CreateMedicationReminder :one
INSERT INTO medication_reminders (
    user_id, medication_name, dosage, frequency, times, start_date, end_date, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, medication_name, dosage, frequency, times, start_date, end_date, is_active, notes, created_at, updated_at
`

type CreateMedicationReminderParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	MedicationName string      `json:"medication_name"`
	Dosage         pgtype.Text `json:"dosage"`
	Frequency      string      `json:"frequency"`
	Times          []string    `json:"times"`
	StartDate      pgtype.Date `json:"start_date"`
	EndDate        pgtype.Date `json:"end_date"`
	Notes          pgtype.Text `json:"notes"`
}

func (q *Queries) CreateMedicationReminder(ctx context.Context, arg CreateMedicationReminderParams) (MedicationReminder, error) {
	row := q.db.QueryRow(ctx, createMedicationReminder,
		arg.UserID,
		arg.MedicationName,
		arg.Dosage,
		arg.Frequency,
		arg.Times,
		arg.StartDate,
		arg.EndDate,
		arg.Notes,
	)
	var i MedicationReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MedicationName,
		&i.Dosage,
		&i.Frequency,
		&i.Times,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFamilyMember = `-- name: DeleteFamilyMember :exec
DELETE FROM family_members WHERE id = $1 AND (caregiver_id = $2 OR patient_id = $2)
`

type DeleteFamilyMemberParams struct {
	ID          pgtype.UUID `json:"id"`
	CaregiverID pgtype.UUID `json:"caregiver_id"`
}

func (q *Queries) DeleteFamilyMember(ctx context.Context, arg DeleteFamilyMemberParams) error {
	_, err := q.db.Exec(ctx, deleteFamilyMember, arg.ID, arg.CaregiverID)
	return err
}

const deleteMedicalRecord = `-- name: DeleteMedicalRecord :exec
DELETE FROM medical_records WHERE id = $1 AND user_id = $2
`

type DeleteMedicalRecordParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMedicalRecord(ctx context.Context, arg DeleteMedicalRecordParams) error {
	_, err := q.db.Exec(ctx, deleteMedicalRecord, arg.ID, arg.UserID)
	return err
}

const deleteMedicationReminder = `-- name: DeleteMedicationReminder :exec
DELETE FROM medication_reminders WHERE id = $1 AND user_id = $2
`

type DeleteMedicationReminderParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteMedicationReminder(ctx context.Context, arg DeleteMedicationReminderParams) error {
	_, err := q.db.Exec(ctx, deleteMedicationReminder, arg.ID, arg.UserID)
	return err
}

const findUserByPhoneOrEmail = `-- name: FindUserByPhoneOrEmail :one
SELECT id, full_name, phone, email FROM users
WHERE phone = $1 OR email = $1 LIMIT 1
`

type FindUserByPhoneOrEmailRow struct {
	ID       pgtype.UUID `json:"id"`
	FullName string      `json:"full_name"`
	Phone    string      `json:"phone"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) FindUserByPhoneOrEmail(ctx context.Context, phone string) (FindUserByPhoneOrEmailRow, error) {
	row := q.db.QueryRow(ctx, findUserByPhoneOrEmail, phone)
	var i FindUserByPhoneOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Phone,
		&i.Email,
	)
	return i, err
}

const getAppointment = `-- name: GetAppointment :one
SELECT a.id, a.user_id, a.merchant_id, a.service_id, a.appointment_date, a.appointment_time, a.duration_min, a.status, a.notes, a.created_at, a.updated_at, m.trade_name AS merchant_name, ms.name AS service_name
FROM appointments a
LEFT JOIN merchants m ON a.merchant_id = m.id
LEFT JOIN medical_services ms ON a.service_id = ms.id
WHERE a.id = $1 AND a.user_id = $2
`

type GetAppointmentParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetAppointmentRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	ServiceID       pgtype.UUID        `json:"service_id"`
	AppointmentDate pgtype.Date        `json:"appointment_date"`
	AppointmentTime pgtype.Time        `json:"appointment_time"`
	DurationMin     int16              `json:"duration_min"`
	Status          string             `json:"status"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
	ServiceName     pgtype.Text        `json:"service_name"`
}

func (q *Queries) GetAppointment(ctx context.Context, arg GetAppointmentParams) (GetAppointmentRow, error) {
	row := q.db.QueryRow(ctx, getAppointment, arg.ID, arg.UserID)
	var i GetAppointmentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.ServiceID,
		&i.AppointmentDate,
		&i.AppointmentTime,
		&i.DurationMin,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.MerchantName,
		&i.ServiceName,
	)
	return i, err
}

const getFamilyMember = `-- name: GetFamilyMember :one
SELECT id, caregiver_id, patient_id, relation, status, permissions, created_at, updated_at FROM family_members WHERE id = $1
`

func (q *Queries) GetFamilyMember(ctx context.Context, id pgtype.UUID) (FamilyMember, error) {
	row := q.db.QueryRow(ctx, getFamilyMember, id)
	var i FamilyMember
	err := row.Scan(
		&i.ID,
		&i.CaregiverID,
		&i.PatientID,
		&i.Relation,
		&i.Status,
		&i.Permissions,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getHealthProfile = `-- name: GetHealthProfile :one

SELECT id, user_id, blood_type, height_cm, weight_kg, allergies, chronic_conditions, current_medications, emergency_contact_name, emergency_contact_phone, emergency_contact_relation, notes, created_at, updated_at FROM health_profiles WHERE user_id = $1
`

// ════════════════════════════════════════════════════════════
// Health Profile
// ════════════════════════════════════════════════════════════
func (q *Queries) GetHealthProfile(ctx context.Context, userID pgtype.UUID) (HealthProfile, error) {
	row := q.db.QueryRow(ctx, getHealthProfile, userID)
	var i HealthProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BloodType,
		&i.HeightCm,
		&i.WeightKg,
		&i.Allergies,
		&i.ChronicConditions,
		&i.CurrentMedications,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.EmergencyContactRelation,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMedicalRecord = `-- name: GetMedicalRecord :one
SELECT id, user_id, transaction_id, merchant_id, service_id, record_type, diagnosis, prescription, doctor_name, notes, record_date, created_at, updated_at FROM medical_records WHERE id = $1 AND user_id = $2
`

type GetMedicalRecordParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMedicalRecord(ctx context.Context, arg GetMedicalRecordParams) (MedicalRecord, error) {
	row := q.db.QueryRow(ctx, getMedicalRecord, arg.ID, arg.UserID)
	var i MedicalRecord
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TransactionID,
		&i.MerchantID,
		&i.ServiceID,
		&i.RecordType,
		&i.Diagnosis,
		&i.Prescription,
		&i.DoctorName,
		&i.Notes,
		&i.RecordDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMedicationReminder = `-- name: GetMedicationReminder :one
SELECT id, user_id, medication_name, dosage, frequency, times, start_date, end_date, is_active, notes, created_at, updated_at FROM medication_reminders WHERE id = $1 AND user_id = $2
`

type GetMedicationReminderParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMedicationReminder(ctx context.Context, arg GetMedicationReminderParams) (MedicationReminder, error) {
	row := q.db.QueryRow(ctx, getMedicationReminder, arg.ID, arg.UserID)
	var i MedicationReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MedicationName,
		&i.Dosage,
		&i.Frequency,
		&i.Times,
		&i.StartDate,
		&i.EndDate,
		&i.IsActive,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointments = `-- name: ListAppointments :many

SELECT a.id, a.user_id, a.merchant_id, a.service_id, a.appointment_date, a.appointment_time, a.duration_min, a.status, a.notes, a.created_at, a.updated_at, m.trade_name AS merchant_name, ms.name AS service_name
FROM appointments a
LEFT JOIN merchants m ON a.merchant_id = m.id
LEFT JOIN medical_services ms ON a.service_id = ms.id
WHERE a.user_id = $1
ORDER BY a.appointment_date DESC, a.appointment_time DESC
LIMIT $2 OFFSET $3
`

type ListAppointmentsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListAppointmentsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	ServiceID       pgtype.UUID        `json:"service_id"`
	AppointmentDate pgtype.Date        `json:"appointment_date"`
	AppointmentTime pgtype.Time        `json:"appointment_time"`
	DurationMin     int16              `json:"duration_min"`
	Status          string             `json:"status"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
	ServiceName     pgtype.Text        `json:"service_name"`
}

// ════════════════════════════════════════════════════════════
// Appointments
// ════════════════════════════════════════════════════════════
func (q *Queries) ListAppointments(ctx context.Context, arg ListAppointmentsParams) ([]ListAppointmentsRow, error) {
	rows, err := q.db.Query(ctx, listAppointments, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppointmentsRow
	for rows.Next() {
		var i ListAppointmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.ServiceID,
			&i.AppointmentDate,
			&i.AppointmentTime,
			&i.DurationMin,
			&i.Status,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MerchantName,
			&i.ServiceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCaregivers = `-- name: ListCaregivers :many
SELECT fm.id, fm.caregiver_id, fm.patient_id, fm.relation, fm.status, fm.permissions, fm.created_at, fm.updated_at, u.full_name AS caregiver_name, u.phone AS caregiver_phone, u.email AS caregiver_email
FROM family_members fm
JOIN users u ON fm.caregiver_id = u.id
WHERE fm.patient_id = $1
ORDER BY fm.created_at DESC
`

type ListCaregiversRow struct {
	ID             pgtype.UUID        `json:"id"`
	CaregiverID    pgtype.UUID        `json:"caregiver_id"`
	PatientID      pgtype.UUID        `json:"patient_id"`
	Relation       pgtype.Text        `json:"relation"`
	Status         string             `json:"status"`
	Permissions    []string           `json:"permissions"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	CaregiverName  string             `json:"caregiver_name"`
	CaregiverPhone string             `json:"caregiver_phone"`
	CaregiverEmail pgtype.Text        `json:"caregiver_email"`
}

func (q *Queries) ListCaregivers(ctx context.Context, patientID pgtype.UUID) ([]ListCaregiversRow, error) {
	rows, err := q.db.Query(ctx, listCaregivers, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCaregiversRow
	for rows.Next() {
		var i ListCaregiversRow
		if err := rows.Scan(
			&i.ID,
			&i.CaregiverID,
			&i.PatientID,
			&i.Relation,
			&i.Status,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CaregiverName,
			&i.CaregiverPhone,
			&i.CaregiverEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFamilyMembers = `-- name: ListFamilyMembers :many

SELECT fm.id, fm.caregiver_id, fm.patient_id, fm.relation, fm.status, fm.permissions, fm.created_at, fm.updated_at, u.full_name AS patient_name, u.phone AS patient_phone, u.email AS patient_email
FROM family_members fm
JOIN users u ON fm.patient_id = u.id
WHERE fm.caregiver_id = $1
ORDER BY fm.created_at DESC
`

type ListFamilyMembersRow struct {
	ID           pgtype.UUID        `json:"id"`
	CaregiverID  pgtype.UUID        `json:"caregiver_id"`
	PatientID    pgtype.UUID        `json:"patient_id"`
	Relation     pgtype.Text        `json:"relation"`
	Status       string             `json:"status"`
	Permissions  []string           `json:"permissions"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PatientName  string             `json:"patient_name"`
	PatientPhone string             `json:"patient_phone"`
	PatientEmail pgtype.Text        `json:"patient_email"`
}

// ════════════════════════════════════════════════════════════
// Family / Caregiver
// ════════════════════════════════════════════════════════════
func (q *Queries) ListFamilyMembers(ctx context.Context, caregiverID pgtype.UUID) ([]ListFamilyMembersRow, error) {
	rows, err := q.db.Query(ctx, listFamilyMembers, caregiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFamilyMembersRow
	for rows.Next() {
		var i ListFamilyMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.CaregiverID,
			&i.PatientID,
			&i.Relation,
			&i.Status,
			&i.Permissions,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PatientName,
			&i.PatientPhone,
			&i.PatientEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicalRecords = `-- name: ListMedicalRecords :many

SELECT id, user_id, transaction_id, merchant_id, service_id, record_type, diagnosis, prescription, doctor_name, notes, record_date, created_at, updated_at FROM medical_records
WHERE user_id = $1
ORDER BY record_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListMedicalRecordsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// ════════════════════════════════════════════════════════════
// Medical Records
// ════════════════════════════════════════════════════════════
func (q *Queries) ListMedicalRecords(ctx context.Context, arg ListMedicalRecordsParams) ([]MedicalRecord, error) {
	rows, err := q.db.Query(ctx, listMedicalRecords, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedicalRecord
	for rows.Next() {
		var i MedicalRecord
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionID,
			&i.MerchantID,
			&i.ServiceID,
			&i.RecordType,
			&i.Diagnosis,
			&i.Prescription,
			&i.DoctorName,
			&i.Notes,
			&i.RecordDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMedicationReminders = `-- name: ListMedicationReminders :many

SELECT id, user_id, medication_name, dosage, frequency, times, start_date, end_date, is_active, notes, created_at, updated_at FROM medication_reminders
WHERE user_id = $1 AND is_active = true
ORDER BY created_at DESC
`

// ════════════════════════════════════════════════════════════
// Medication Reminders
// ════════════════════════════════════════════════════════════
func (q *Queries) ListMedicationReminders(ctx context.Context, userID pgtype.UUID) ([]MedicationReminder, error) {
	rows, err := q.db.Query(ctx, listMedicationReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MedicationReminder
	for rows.Next() {
		var i MedicationReminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MedicationName,
			&i.Dosage,
			&i.Frequency,
			&i.Times,
			&i.StartDate,
			&i.EndDate,
			&i.IsActive,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :exec
UPDATE appointments SET status = $3
WHERE id = $1 AND (user_id = $2 OR $2 = '')
RETURNING id
`

type UpdateAppointmentStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateAppointmentStatus, arg.ID, arg.UserID, arg.Status)
	return err
}

const updateFamilyMemberPermissions = `-- name: UpdateFamilyMemberPermissions :exec
UPDATE family_members SET permissions = $3 WHERE id = $1 AND caregiver_id = $2
`

type UpdateFamilyMemberPermissionsParams struct {
	ID          pgtype.UUID `json:"id"`
	CaregiverID pgtype.UUID `json:"caregiver_id"`
	Permissions []string    `json:"permissions"`
}

func (q *Queries) UpdateFamilyMemberPermissions(ctx context.Context, arg UpdateFamilyMemberPermissionsParams) error {
	_, err := q.db.Exec(ctx, updateFamilyMemberPermissions, arg.ID, arg.CaregiverID, arg.Permissions)
	return err
}

const updateFamilyMemberStatus = `-- name: UpdateFamilyMemberStatus :exec
UPDATE family_members SET status = $3 WHERE id = $1 AND (caregiver_id = $2 OR patient_id = $2)
`

type UpdateFamilyMemberStatusParams struct {
	ID          pgtype.UUID `json:"id"`
	CaregiverID pgtype.UUID `json:"caregiver_id"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateFamilyMemberStatus(ctx context.Context, arg UpdateFamilyMemberStatusParams) error {
	_, err := q.db.Exec(ctx, updateFamilyMemberStatus, arg.ID, arg.CaregiverID, arg.Status)
	return err
}

const updateMedicalRecord = `-- name: UpdateMedicalRecord :exec
UPDATE medical_records
SET record_type = $3, diagnosis = $4, prescription = $5,
    doctor_name = $6, notes = $7, record_date = $8
WHERE id = $1 AND user_id = $2
`

type UpdateMedicalRecordParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	RecordType   string      `json:"record_type"`
	Diagnosis    pgtype.Text `json:"diagnosis"`
	Prescription pgtype.Text `json:"prescription"`
	DoctorName   pgtype.Text `json:"doctor_name"`
	Notes        pgtype.Text `json:"notes"`
	RecordDate   pgtype.Date `json:"record_date"`
}

func (q *Queries) UpdateMedicalRecord(ctx context.Context, arg UpdateMedicalRecordParams) error {
	_, err := q.db.Exec(ctx, updateMedicalRecord,
		arg.ID,
		arg.UserID,
		arg.RecordType,
		arg.Diagnosis,
		arg.Prescription,
		arg.DoctorName,
		arg.Notes,
		arg.RecordDate,
	)
	return err
}

const updateMedicationReminder = `-- name: UpdateMedicationReminder :exec
UPDATE medication_reminders
SET medication_name = $3, dosage = $4, frequency = $5, times = $6,
    end_date = $7, is_active = $8, notes = $9
WHERE id = $1 AND user_id = $2
`

type UpdateMedicationReminderParams struct {
	ID             pgtype.UUID `json:"id"`
	UserID         pgtype.UUID `json:"user_id"`
	MedicationName string      `json:"medication_name"`
	Dosage         pgtype.Text `json:"dosage"`
	Frequency      string      `json:"frequency"`
	Times          []string    `json:"times"`
	EndDate        pgtype.Date `json:"end_date"`
	IsActive       bool        `json:"is_active"`
	Notes          pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateMedicationReminder(ctx context.Context, arg UpdateMedicationReminderParams) error {
	_, err := q.db.Exec(ctx, updateMedicationReminder,
		arg.ID,
		arg.UserID,
		arg.MedicationName,
		arg.Dosage,
		arg.Frequency,
		arg.Times,
		arg.EndDate,
		arg.IsActive,
		arg.Notes,
	)
	return err
}

const upsertHealthProfile = `-- name: UpsertHealthProfile :one
INSERT INTO health_profiles (
    user_id, blood_type, height_cm, weight_kg,
    allergies, chronic_conditions, current_medications,
    emergency_contact_name, emergency_contact_phone, emergency_contact_relation, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (user_id) DO UPDATE SET
    blood_type = EXCLUDED.blood_type,
    height_cm = EXCLUDED.height_cm,
    weight_kg = EXCLUDED.weight_kg,
    allergies = EXCLUDED.allergies,
    chronic_conditions = EXCLUDED.chronic_conditions,
    current_medications = EXCLUDED.current_medications,
    emergency_contact_name = EXCLUDED.emergency_contact_name,
    emergency_contact_phone = EXCLUDED.emergency_contact_phone,
    emergency_contact_relation = EXCLUDED.emergency_contact_relation,
    notes = EXCLUDED.notes,
    updated_at = NOW()
RETURNING id, user_id, blood_type, height_cm, weight_kg, allergies, chronic_conditions, current_medications, emergency_contact_name, emergency_contact_phone, emergency_contact_relation, notes, created_at, updated_at
`

type UpsertHealthProfileParams struct {
	UserID                   pgtype.UUID    `json:"user_id"`
	BloodType                pgtype.Text    `json:"blood_type"`
	HeightCm                 pgtype.Int2    `json:"height_cm"`
	WeightKg                 pgtype.Numeric `json:"weight_kg"`
	Allergies                []string       `json:"allergies"`
	ChronicConditions        []string       `json:"chronic_conditions"`
	CurrentMedications       []string       `json:"current_medications"`
	EmergencyContactName     pgtype.Text    `json:"emergency_contact_name"`
	EmergencyContactPhone    pgtype.Text    `json:"emergency_contact_phone"`
	EmergencyContactRelation pgtype.Text    `json:"emergency_contact_relation"`
	Notes                    pgtype.Text    `json:"notes"`
}

func (q *Queries) UpsertHealthProfile(ctx context.Context, arg UpsertHealthProfileParams) (HealthProfile, error) {
	row := q.db.QueryRow(ctx, upsertHealthProfile,
		arg.UserID,
		arg.BloodType,
		arg.HeightCm,
		arg.WeightKg,
		arg.Allergies,
		arg.ChronicConditions,
		arg.CurrentMedications,
		arg.EmergencyContactName,
		arg.EmergencyContactPhone,
		arg.EmergencyContactRelation,
		arg.Notes,
	)
	var i HealthProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BloodType,
		&i.HeightCm,
		&i.WeightKg,
		&i.Allergies,
		&i.ChronicConditions,
		&i.CurrentMedications,
		&i.EmergencyContactName,
		&i.EmergencyContactPhone,
		&i.EmergencyContactRelation,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
