// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMerchantByID = `-- name: GetMerchantByID :one
SELECT id, legal_name, trade_name, rif, category, address, city, phone, email, contact_name, mdr_rate, bank_account_bs, bank_account_usd, is_active, is_online, min_transaction, created_at, updated_at, subcategory FROM merchants WHERE id = $1
`

func (q *Queries) GetMerchantByID(ctx context.Context, id pgtype.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchantByID, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.LegalName,
		&i.TradeName,
		&i.Rif,
		&i.Category,
		&i.Address,
		&i.City,
		&i.Phone,
		&i.Email,
		&i.ContactName,
		&i.MdrRate,
		&i.BankAccountBs,
		&i.BankAccountUsd,
		&i.IsActive,
		&i.IsOnline,
		&i.MinTransaction,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subcategory,
	)
	return i, err
}

const getMerchantPayouts = `-- name: GetMerchantPayouts :many
SELECT 
    m.id AS merchant_id,
    m.trade_name AS merchant_name,
    COUNT(t.id) AS total_transactions,
    SUM(t.financed_amount) AS total_financed,
    SUM(t.mdr_fee) AS total_fees,
    (SUM(t.financed_amount) - SUM(t.mdr_fee)) AS net_payout
FROM merchants m
JOIN transactions t ON m.id = t.merchant_id
WHERE t.created_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY m.id, m.trade_name
`

type GetMerchantPayoutsRow struct {
	MerchantID        pgtype.UUID `json:"merchant_id"`
	MerchantName      string      `json:"merchant_name"`
	TotalTransactions int64       `json:"total_transactions"`
	TotalFinanced     int64       `json:"total_financed"`
	TotalFees         int64       `json:"total_fees"`
	NetPayout         int32       `json:"net_payout"`
}

func (q *Queries) GetMerchantPayouts(ctx context.Context) ([]GetMerchantPayoutsRow, error) {
	rows, err := q.db.Query(ctx, getMerchantPayouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMerchantPayoutsRow
	for rows.Next() {
		var i GetMerchantPayoutsRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.MerchantName,
			&i.TotalTransactions,
			&i.TotalFinanced,
			&i.TotalFees,
			&i.NetPayout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
