// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchant.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMerchantPayouts = `-- name: GetMerchantPayouts :many
SELECT 
    m.id AS merchant_id,
    m.trade_name AS merchant_name,
    COUNT(t.id) AS total_transactions,
    SUM(t.financed_amount) AS total_financed,
    SUM(t.mdr_fee) AS total_fees,
    (SUM(t.financed_amount) - SUM(t.mdr_fee)) AS net_payout
FROM merchants m
JOIN transactions t ON m.id = t.merchant_id
WHERE t.created_at >= CURRENT_DATE - INTERVAL '30 days'
GROUP BY m.id, m.trade_name
`

type GetMerchantPayoutsRow struct {
	MerchantID        pgtype.UUID `json:"merchant_id"`
	MerchantName      string      `json:"merchant_name"`
	TotalTransactions int64       `json:"total_transactions"`
	TotalFinanced     int64       `json:"total_financed"`
	TotalFees         int64       `json:"total_fees"`
	NetPayout         int32       `json:"net_payout"`
}

func (q *Queries) GetMerchantPayouts(ctx context.Context) ([]GetMerchantPayoutsRow, error) {
	rows, err := q.db.Query(ctx, getMerchantPayouts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMerchantPayoutsRow
	for rows.Next() {
		var i GetMerchantPayoutsRow
		if err := rows.Scan(
			&i.MerchantID,
			&i.MerchantName,
			&i.TotalTransactions,
			&i.TotalFinanced,
			&i.TotalFees,
			&i.NetPayout,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
