// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type CreditLineStatus string

const (
	CreditLineStatusACTIVE  CreditLineStatus = "ACTIVE"
	CreditLineStatusPAUSED  CreditLineStatus = "PAUSED"
	CreditLineStatusBLOCKED CreditLineStatus = "BLOCKED"
)

func (e *CreditLineStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CreditLineStatus(s)
	case string:
		*e = CreditLineStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CreditLineStatus: %T", src)
	}
	return nil
}

type NullCreditLineStatus struct {
	CreditLineStatus CreditLineStatus `json:"credit_line_status"`
	Valid            bool             `json:"valid"` // Valid is true if CreditLineStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCreditLineStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CreditLineStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CreditLineStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCreditLineStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CreditLineStatus), nil
}

type InstallmentStatus string

const (
	InstallmentStatusPENDING InstallmentStatus = "PENDING"
	InstallmentStatusPAID    InstallmentStatus = "PAID"
	InstallmentStatusOVERDUE InstallmentStatus = "OVERDUE"
	InstallmentStatusWAIVED  InstallmentStatus = "WAIVED"
)

func (e *InstallmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstallmentStatus(s)
	case string:
		*e = InstallmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InstallmentStatus: %T", src)
	}
	return nil
}

type NullInstallmentStatus struct {
	InstallmentStatus InstallmentStatus `json:"installment_status"`
	Valid             bool              `json:"valid"` // Valid is true if InstallmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstallmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InstallmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstallmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstallmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstallmentStatus), nil
}

type TransactionStatus string

const (
	TransactionStatusPENDINGPAYMENT TransactionStatus = "PENDING_PAYMENT"
	TransactionStatusACTIVE         TransactionStatus = "ACTIVE"
	TransactionStatusCOMPLETED      TransactionStatus = "COMPLETED"
	TransactionStatusCANCELLED      TransactionStatus = "CANCELLED"
	TransactionStatusREFUNDED       TransactionStatus = "REFUNDED"
)

func (e *TransactionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransactionStatus(s)
	case string:
		*e = TransactionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TransactionStatus: %T", src)
	}
	return nil
}

type NullTransactionStatus struct {
	TransactionStatus TransactionStatus `json:"transaction_status"`
	Valid             bool              `json:"valid"` // Valid is true if TransactionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransactionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TransactionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransactionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransactionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransactionStatus), nil
}

type UserRole string

const (
	UserRolePATIENT  UserRole = "PATIENT"
	UserRoleMERCHANT UserRole = "MERCHANT"
	UserRoleADMIN    UserRole = "ADMIN"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Details   pgtype.Text        `json:"details"`
	IpAddress pgtype.Text        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CreditLine struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Type          string             `json:"type"`
	LimitUsd      pgtype.Numeric     `json:"limit_usd"`
	UsedUsd       pgtype.Numeric     `json:"used_usd"`
	Status        string             `json:"status"`
	PausedAt      pgtype.Timestamptz `json:"paused_at"`
	ReactivatedAt pgtype.Timestamptz `json:"reactivated_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type ElderCareSubscription struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	ServiceType     string             `json:"service_type"`
	MonthlyAmount   pgtype.Numeric     `json:"monthly_amount"`
	Status          string             `json:"status"`
	NextBillingDate pgtype.Timestamptz `json:"next_billing_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Installment struct {
	ID              pgtype.UUID        `json:"id"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	InstallmentNum  int16              `json:"installment_num"`
	Amount          pgtype.Numeric     `json:"amount"`
	DueDate         pgtype.Date        `json:"due_date"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	Status          string             `json:"status"`
	ReactivationFee pgtype.Numeric     `json:"reactivation_fee"`
	DaysOverdue     int32              `json:"days_overdue"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Merchant struct {
	ID             pgtype.UUID        `json:"id"`
	LegalName      string             `json:"legal_name"`
	TradeName      string             `json:"trade_name"`
	Rif            string             `json:"rif"`
	Category       string             `json:"category"`
	Address        pgtype.Text        `json:"address"`
	City           pgtype.Text        `json:"city"`
	Phone          pgtype.Text        `json:"phone"`
	Email          string             `json:"email"`
	ContactName    pgtype.Text        `json:"contact_name"`
	MdrRate        pgtype.Numeric     `json:"mdr_rate"`
	BankAccountBs  pgtype.Text        `json:"bank_account_bs"`
	BankAccountUsd pgtype.Text        `json:"bank_account_usd"`
	IsActive       bool               `json:"is_active"`
	IsOnline       bool               `json:"is_online"`
	MinTransaction pgtype.Numeric     `json:"min_transaction"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Subcategory    pgtype.Text        `json:"subcategory"`
}

type MerchantPayout struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	PeriodStart pgtype.Date        `json:"period_start"`
	PeriodEnd   pgtype.Date        `json:"period_end"`
	GrossAmount pgtype.Numeric     `json:"gross_amount"`
	MdrDeducted pgtype.Numeric     `json:"mdr_deducted"`
	NetAmount   pgtype.Numeric     `json:"net_amount"`
	Status      string             `json:"status"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MerchantUser struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	UserID     pgtype.UUID `json:"user_id"`
	IsOwner    bool        `json:"is_owner"`
}

type Payment struct {
	ID            pgtype.UUID        `json:"id"`
	InstallmentID pgtype.UUID        `json:"installment_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	AmountPaid    pgtype.Numeric     `json:"amount_paid"`
	PaymentMethod string             `json:"payment_method"`
	ReferenceCode pgtype.Text        `json:"reference_code"`
	Verified      bool               `json:"verified"`
	VerifiedBy    pgtype.UUID        `json:"verified_by"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
}

type Subscription struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	ProductName     string             `json:"product_name"`
	Status          string             `json:"status"`
	NextBillingDate pgtype.Timestamptz `json:"next_billing_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	DownPayment     pgtype.Numeric     `json:"down_payment"`
	FinancedAmount  pgtype.Numeric     `json:"financed_amount"`
	NumInstallments int16              `json:"num_installments"`
	Status          string             `json:"status"`
	QrCodeToken     pgtype.Text        `json:"qr_code_token"`
	QrExpiresAt     pgtype.Timestamptz `json:"qr_expires_at"`
	MdrFee          pgtype.Numeric     `json:"mdr_fee"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                         pgtype.UUID        `json:"id"`
	Phone                      string             `json:"phone"`
	Email                      pgtype.Text        `json:"email"`
	PasswordHash               string             `json:"password_hash"`
	FullName                   string             `json:"full_name"`
	NationalID                 pgtype.Text        `json:"national_id"`
	Role                       string             `json:"role"`
	Level                      int16              `json:"level"`
	Points                     int32              `json:"points"`
	TotalPaid                  pgtype.Numeric     `json:"total_paid"`
	InstallmentsPaidCount      int32              `json:"installments_paid_count"`
	IsActive                   bool               `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	IsPhoneVerified            bool               `json:"is_phone_verified"`
	IsCreditFrozenForElectives bool               `json:"is_credit_frozen_for_electives"`
}

type UserGamificationHistory struct {
	ID            pgtype.UUID      `json:"id"`
	UserID        pgtype.UUID      `json:"user_id"`
	EventType     string           `json:"event_type"`
	PointsAwarded int32            `json:"points_awarded"`
	Description   pgtype.Text      `json:"description"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

type UserLevelHistory struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FromLevel pgtype.Int2        `json:"from_level"`
	ToLevel   int16              `json:"to_level"`
	Reason    pgtype.Text        `json:"reason"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}
