// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	ServiceID       pgtype.UUID        `json:"service_id"`
	AppointmentDate pgtype.Date        `json:"appointment_date"`
	AppointmentTime pgtype.Time        `json:"appointment_time"`
	DurationMin     int16              `json:"duration_min"`
	Status          string             `json:"status"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID        int64              `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Action    string             `json:"action"`
	Entity    string             `json:"entity"`
	EntityID  pgtype.UUID        `json:"entity_id"`
	Details   pgtype.Text        `json:"details"`
	IpAddress pgtype.Text        `json:"ip_address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type CreditLine struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Type          string             `json:"type"`
	LimitUsd      pgtype.Numeric     `json:"limit_usd"`
	UsedUsd       pgtype.Numeric     `json:"used_usd"`
	Status        string             `json:"status"`
	PausedAt      pgtype.Timestamptz `json:"paused_at"`
	ReactivatedAt pgtype.Timestamptz `json:"reactivated_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	BlockedAt     pgtype.Timestamptz `json:"blocked_at"`
}

type ElderCareSubscription struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	ServiceType     string             `json:"service_type"`
	MonthlyAmount   pgtype.Numeric     `json:"monthly_amount"`
	Status          string             `json:"status"`
	NextBillingDate pgtype.Timestamptz `json:"next_billing_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type FamilyMember struct {
	ID          pgtype.UUID        `json:"id"`
	CaregiverID pgtype.UUID        `json:"caregiver_id"`
	PatientID   pgtype.UUID        `json:"patient_id"`
	Relation    pgtype.Text        `json:"relation"`
	Status      string             `json:"status"`
	Permissions []string           `json:"permissions"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type HealthProfile struct {
	ID                       pgtype.UUID        `json:"id"`
	UserID                   pgtype.UUID        `json:"user_id"`
	BloodType                pgtype.Text        `json:"blood_type"`
	HeightCm                 pgtype.Int2        `json:"height_cm"`
	WeightKg                 pgtype.Numeric     `json:"weight_kg"`
	Allergies                []string           `json:"allergies"`
	ChronicConditions        []string           `json:"chronic_conditions"`
	CurrentMedications       []string           `json:"current_medications"`
	EmergencyContactName     pgtype.Text        `json:"emergency_contact_name"`
	EmergencyContactPhone    pgtype.Text        `json:"emergency_contact_phone"`
	EmergencyContactRelation pgtype.Text        `json:"emergency_contact_relation"`
	Notes                    pgtype.Text        `json:"notes"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
}

type Installment struct {
	ID              pgtype.UUID        `json:"id"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	InstallmentNum  int16              `json:"installment_num"`
	Amount          pgtype.Numeric     `json:"amount"`
	DueDate         pgtype.Date        `json:"due_date"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	Status          string             `json:"status"`
	ReactivationFee pgtype.Numeric     `json:"reactivation_fee"`
	DaysOverdue     int32              `json:"days_overdue"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MedicalRecord struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	ServiceID     pgtype.UUID        `json:"service_id"`
	RecordType    string             `json:"record_type"`
	Diagnosis     pgtype.Text        `json:"diagnosis"`
	Prescription  pgtype.Text        `json:"prescription"`
	DoctorName    pgtype.Text        `json:"doctor_name"`
	Notes         pgtype.Text        `json:"notes"`
	RecordDate    pgtype.Date        `json:"record_date"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MedicalService struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Category    string             `json:"category"`
	Subcategory pgtype.Text        `json:"subcategory"`
	PriceUsd    pgtype.Numeric     `json:"price_usd"`
	DurationMin pgtype.Int2        `json:"duration_min"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MedicalSupply struct {
	ID                   pgtype.UUID        `json:"id"`
	MerchantID           pgtype.UUID        `json:"merchant_id"`
	Name                 string             `json:"name"`
	Description          pgtype.Text        `json:"description"`
	Category             string             `json:"category"`
	Subcategory          pgtype.Text        `json:"subcategory"`
	PriceUsd             pgtype.Numeric     `json:"price_usd"`
	Unit                 pgtype.Text        `json:"unit"`
	Stock                int32              `json:"stock"`
	MinStock             pgtype.Int4        `json:"min_stock"`
	RequiresPrescription bool               `json:"requires_prescription"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type MedicationReminder struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	MedicationName string             `json:"medication_name"`
	Dosage         pgtype.Text        `json:"dosage"`
	Frequency      string             `json:"frequency"`
	Times          []string           `json:"times"`
	StartDate      pgtype.Date        `json:"start_date"`
	EndDate        pgtype.Date        `json:"end_date"`
	IsActive       bool               `json:"is_active"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Merchant struct {
	ID             pgtype.UUID        `json:"id"`
	LegalName      string             `json:"legal_name"`
	TradeName      string             `json:"trade_name"`
	Rif            string             `json:"rif"`
	Category       string             `json:"category"`
	Address        pgtype.Text        `json:"address"`
	City           pgtype.Text        `json:"city"`
	Phone          pgtype.Text        `json:"phone"`
	Email          string             `json:"email"`
	ContactName    pgtype.Text        `json:"contact_name"`
	MdrRate        pgtype.Numeric     `json:"mdr_rate"`
	BankAccountBs  pgtype.Text        `json:"bank_account_bs"`
	BankAccountUsd pgtype.Text        `json:"bank_account_usd"`
	IsActive       bool               `json:"is_active"`
	IsOnline       bool               `json:"is_online"`
	MinTransaction pgtype.Numeric     `json:"min_transaction"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Subcategory    pgtype.Text        `json:"subcategory"`
}

type MerchantPayout struct {
	ID          pgtype.UUID        `json:"id"`
	MerchantID  pgtype.UUID        `json:"merchant_id"`
	PeriodStart pgtype.Date        `json:"period_start"`
	PeriodEnd   pgtype.Date        `json:"period_end"`
	GrossAmount pgtype.Numeric     `json:"gross_amount"`
	MdrDeducted pgtype.Numeric     `json:"mdr_deducted"`
	NetAmount   pgtype.Numeric     `json:"net_amount"`
	Status      string             `json:"status"`
	PaidAt      pgtype.Timestamptz `json:"paid_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type MerchantUser struct {
	ID         pgtype.UUID `json:"id"`
	MerchantID pgtype.UUID `json:"merchant_id"`
	UserID     pgtype.UUID `json:"user_id"`
	IsOwner    bool        `json:"is_owner"`
}

type Payment struct {
	ID            pgtype.UUID        `json:"id"`
	InstallmentID pgtype.UUID        `json:"installment_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	AmountPaid    pgtype.Numeric     `json:"amount_paid"`
	PaymentMethod string             `json:"payment_method"`
	ReferenceCode pgtype.Text        `json:"reference_code"`
	Verified      bool               `json:"verified"`
	VerifiedBy    pgtype.UUID        `json:"verified_by"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
}

type QrToken struct {
	ID            pgtype.UUID        `json:"id"`
	Token         string             `json:"token"`
	MerchantID    pgtype.UUID        `json:"merchant_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Description   pgtype.Text        `json:"description"`
	Status        string             `json:"status"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type Subscription struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	ProductName     string             `json:"product_name"`
	Status          string             `json:"status"`
	NextBillingDate pgtype.Timestamptz `json:"next_billing_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type SubscriptionItem struct {
	ID             pgtype.UUID    `json:"id"`
	SubscriptionID pgtype.UUID    `json:"subscription_id"`
	SupplyID       pgtype.UUID    `json:"supply_id"`
	ItemName       string         `json:"item_name"`
	Quantity       int16          `json:"quantity"`
	UnitPriceUsd   pgtype.Numeric `json:"unit_price_usd"`
}

type Transaction struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	DownPayment     pgtype.Numeric     `json:"down_payment"`
	FinancedAmount  pgtype.Numeric     `json:"financed_amount"`
	NumInstallments int16              `json:"num_installments"`
	Status          string             `json:"status"`
	QrCodeToken     pgtype.Text        `json:"qr_code_token"`
	QrExpiresAt     pgtype.Timestamptz `json:"qr_expires_at"`
	MdrFee          pgtype.Numeric     `json:"mdr_fee"`
	Description     pgtype.Text        `json:"description"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TransactionItem struct {
	ID            pgtype.UUID        `json:"id"`
	TransactionID pgtype.UUID        `json:"transaction_id"`
	ServiceID     pgtype.UUID        `json:"service_id"`
	SupplyID      pgtype.UUID        `json:"supply_id"`
	ItemName      string             `json:"item_name"`
	Quantity      int16              `json:"quantity"`
	UnitPriceUsd  pgtype.Numeric     `json:"unit_price_usd"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Triage struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Symptoms          string             `json:"symptoms"`
	PerceivedSeverity int16              `json:"perceived_severity"`
	Priority          string             `json:"priority"`
	Status            string             `json:"status"`
	Recommendation    pgtype.Text        `json:"recommendation"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                         pgtype.UUID        `json:"id"`
	Phone                      string             `json:"phone"`
	Email                      pgtype.Text        `json:"email"`
	PasswordHash               string             `json:"password_hash"`
	FullName                   string             `json:"full_name"`
	NationalID                 pgtype.Text        `json:"national_id"`
	Role                       string             `json:"role"`
	Level                      int16              `json:"level"`
	Points                     int32              `json:"points"`
	TotalPaid                  pgtype.Numeric     `json:"total_paid"`
	InstallmentsPaidCount      int32              `json:"installments_paid_count"`
	IsActive                   bool               `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	IsPhoneVerified            bool               `json:"is_phone_verified"`
	IsCreditFrozenForElectives bool               `json:"is_credit_frozen_for_electives"`
	IsEmailVerified            bool               `json:"is_email_verified"`
}

type UserGamificationHistory struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	EventType     string             `json:"event_type"`
	PointsAwarded int32              `json:"points_awarded"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type UserLevelHistory struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	FromLevel pgtype.Int2        `json:"from_level"`
	ToLevel   int16              `json:"to_level"`
	Reason    pgtype.Text        `json:"reason"`
	ChangedAt pgtype.Timestamptz `json:"changed_at"`
}
