// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: patient.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelElderCareSub = `-- name: CancelElderCareSub :exec
UPDATE elder_care_subscriptions SET status = 'CANCELLED' WHERE id = $1 AND user_id = $2
`

type CancelElderCareSubParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CancelElderCareSub(ctx context.Context, arg CancelElderCareSubParams) error {
	_, err := q.db.Exec(ctx, cancelElderCareSub, arg.ID, arg.UserID)
	return err
}

const cancelSubscription = `-- name: CancelSubscription :exec
UPDATE subscriptions SET status = 'CANCELLED' WHERE id = $1 AND user_id = $2
`

type CancelSubscriptionParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) error {
	_, err := q.db.Exec(ctx, cancelSubscription, arg.ID, arg.UserID)
	return err
}

const createElderCareSub = `-- name: CreateElderCareSub :one
INSERT INTO elder_care_subscriptions (
    user_id, merchant_id, credit_line_id, service_type, monthly_amount, status, next_billing_date
) VALUES (
    $1, $2, $3, $4, $5, 'ACTIVE', NOW() + INTERVAL '30 days'
) RETURNING id, user_id, merchant_id, credit_line_id, service_type, monthly_amount, status, next_billing_date, created_at, updated_at
`

type CreateElderCareSubParams struct {
	UserID        pgtype.UUID    `json:"user_id"`
	MerchantID    pgtype.UUID    `json:"merchant_id"`
	CreditLineID  pgtype.UUID    `json:"credit_line_id"`
	ServiceType   string         `json:"service_type"`
	MonthlyAmount pgtype.Numeric `json:"monthly_amount"`
}

func (q *Queries) CreateElderCareSub(ctx context.Context, arg CreateElderCareSubParams) (ElderCareSubscription, error) {
	row := q.db.QueryRow(ctx, createElderCareSub,
		arg.UserID,
		arg.MerchantID,
		arg.CreditLineID,
		arg.ServiceType,
		arg.MonthlyAmount,
	)
	var i ElderCareSubscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.CreditLineID,
		&i.ServiceType,
		&i.MonthlyAmount,
		&i.Status,
		&i.NextBillingDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentRecord = `-- name: CreatePaymentRecord :one
INSERT INTO payments (
    installment_id, user_id, amount_paid, payment_method, reference_code, verified, paid_at
) VALUES (
    $1, $2, $3, $4, $5, false, NOW()
) RETURNING id, installment_id, user_id, amount_paid, payment_method, reference_code, verified, verified_by, paid_at
`

type CreatePaymentRecordParams struct {
	InstallmentID pgtype.UUID    `json:"installment_id"`
	UserID        pgtype.UUID    `json:"user_id"`
	AmountPaid    pgtype.Numeric `json:"amount_paid"`
	PaymentMethod string         `json:"payment_method"`
	ReferenceCode pgtype.Text    `json:"reference_code"`
}

func (q *Queries) CreatePaymentRecord(ctx context.Context, arg CreatePaymentRecordParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPaymentRecord,
		arg.InstallmentID,
		arg.UserID,
		arg.AmountPaid,
		arg.PaymentMethod,
		arg.ReferenceCode,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InstallmentID,
		&i.UserID,
		&i.AmountPaid,
		&i.PaymentMethod,
		&i.ReferenceCode,
		&i.Verified,
		&i.VerifiedBy,
		&i.PaidAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    user_id, merchant_id, credit_line_id, amount, product_name, status, next_billing_date
) VALUES (
    $1, $2, $3, $4, $5, 'ACTIVE', NOW() + INTERVAL '30 days'
) RETURNING id, user_id, merchant_id, credit_line_id, amount, product_name, status, next_billing_date, created_at, updated_at
`

type CreateSubscriptionParams struct {
	UserID       pgtype.UUID    `json:"user_id"`
	MerchantID   pgtype.UUID    `json:"merchant_id"`
	CreditLineID pgtype.UUID    `json:"credit_line_id"`
	Amount       pgtype.Numeric `json:"amount"`
	ProductName  string         `json:"product_name"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.UserID,
		arg.MerchantID,
		arg.CreditLineID,
		arg.Amount,
		arg.ProductName,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.CreditLineID,
		&i.Amount,
		&i.ProductName,
		&i.Status,
		&i.NextBillingDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllActiveMerchants = `-- name: GetAllActiveMerchants :many
SELECT id, trade_name, category, city FROM merchants WHERE is_active = true ORDER BY trade_name
`

type GetAllActiveMerchantsRow struct {
	ID        pgtype.UUID `json:"id"`
	TradeName string      `json:"trade_name"`
	Category  string      `json:"category"`
	City      pgtype.Text `json:"city"`
}

func (q *Queries) GetAllActiveMerchants(ctx context.Context) ([]GetAllActiveMerchantsRow, error) {
	rows, err := q.db.Query(ctx, getAllActiveMerchants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllActiveMerchantsRow
	for rows.Next() {
		var i GetAllActiveMerchantsRow
		if err := rows.Scan(
			&i.ID,
			&i.TradeName,
			&i.Category,
			&i.City,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getElderCareSubsByUser = `-- name: GetElderCareSubsByUser :many
SELECT
    e.id, e.user_id, e.merchant_id, e.credit_line_id, e.service_type,
    e.monthly_amount, e.status, e.next_billing_date, e.created_at, e.updated_at,
    m.trade_name AS merchant_name
FROM elder_care_subscriptions e
LEFT JOIN merchants m ON e.merchant_id = m.id
WHERE e.user_id = $1
ORDER BY e.created_at DESC
`

type GetElderCareSubsByUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	ServiceType     string             `json:"service_type"`
	MonthlyAmount   pgtype.Numeric     `json:"monthly_amount"`
	Status          string             `json:"status"`
	NextBillingDate pgtype.Timestamptz `json:"next_billing_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
}

func (q *Queries) GetElderCareSubsByUser(ctx context.Context, userID pgtype.UUID) ([]GetElderCareSubsByUserRow, error) {
	rows, err := q.db.Query(ctx, getElderCareSubsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetElderCareSubsByUserRow
	for rows.Next() {
		var i GetElderCareSubsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.CreditLineID,
			&i.ServiceType,
			&i.MonthlyAmount,
			&i.Status,
			&i.NextBillingDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInstallmentWithDetails = `-- name: GetInstallmentWithDetails :one
SELECT
    i.id AS installment_id,
    i.transaction_id,
    i.user_id,
    i.installment_num,
    i.amount,
    i.due_date,
    i.paid_at,
    i.status,
    i.reactivation_fee,
    i.days_overdue,
    t.id AS transaction_id,
    t.total_amount,
    t.num_installments,
    t.merchant_id,
    t.credit_line_id,
    m.trade_name AS merchant_name
FROM installments i
JOIN transactions t ON i.transaction_id = t.id
LEFT JOIN merchants m ON t.merchant_id = m.id
WHERE i.id = $1 AND i.user_id = $2
`

type GetInstallmentWithDetailsParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

type GetInstallmentWithDetailsRow struct {
	InstallmentID   pgtype.UUID        `json:"installment_id"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	InstallmentNum  int16              `json:"installment_num"`
	Amount          pgtype.Numeric     `json:"amount"`
	DueDate         pgtype.Date        `json:"due_date"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	Status          string             `json:"status"`
	ReactivationFee pgtype.Numeric     `json:"reactivation_fee"`
	DaysOverdue     int32              `json:"days_overdue"`
	TransactionID_2 pgtype.UUID        `json:"transaction_id_2"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	NumInstallments int16              `json:"num_installments"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
}

func (q *Queries) GetInstallmentWithDetails(ctx context.Context, arg GetInstallmentWithDetailsParams) (GetInstallmentWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getInstallmentWithDetails, arg.ID, arg.UserID)
	var i GetInstallmentWithDetailsRow
	err := row.Scan(
		&i.InstallmentID,
		&i.TransactionID,
		&i.UserID,
		&i.InstallmentNum,
		&i.Amount,
		&i.DueDate,
		&i.PaidAt,
		&i.Status,
		&i.ReactivationFee,
		&i.DaysOverdue,
		&i.TransactionID_2,
		&i.TotalAmount,
		&i.NumInstallments,
		&i.MerchantID,
		&i.CreditLineID,
		&i.MerchantName,
	)
	return i, err
}

const getInstallmentsByTransaction = `-- name: GetInstallmentsByTransaction :many
SELECT id, transaction_id, user_id, installment_num, amount, due_date, paid_at, status, reactivation_fee, days_overdue, created_at, updated_at FROM installments WHERE transaction_id = $1 ORDER BY installment_num ASC
`

func (q *Queries) GetInstallmentsByTransaction(ctx context.Context, transactionID pgtype.UUID) ([]Installment, error) {
	rows, err := q.db.Query(ctx, getInstallmentsByTransaction, transactionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Installment
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.UserID,
			&i.InstallmentNum,
			&i.Amount,
			&i.DueDate,
			&i.PaidAt,
			&i.Status,
			&i.ReactivationFee,
			&i.DaysOverdue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT id, installment_id, user_id, amount_paid, payment_method, reference_code, verified, verified_by, paid_at FROM payments WHERE reference_code = $1 LIMIT 1
`

func (q *Queries) GetPaymentByReference(ctx context.Context, referenceCode pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByReference, referenceCode)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.InstallmentID,
		&i.UserID,
		&i.AmountPaid,
		&i.PaymentMethod,
		&i.ReferenceCode,
		&i.Verified,
		&i.VerifiedBy,
		&i.PaidAt,
	)
	return i, err
}

const getPendingInstallmentsWithDetails = `-- name: GetPendingInstallmentsWithDetails :many
SELECT
    i.id AS installment_id,
    i.transaction_id,
    i.user_id,
    i.installment_num,
    i.amount,
    i.due_date,
    i.paid_at,
    i.status,
    i.reactivation_fee,
    i.days_overdue,
    t.id AS transaction_id,
    t.total_amount,
    t.num_installments,
    t.merchant_id,
    m.trade_name AS merchant_name
FROM installments i
JOIN transactions t ON i.transaction_id = t.id
LEFT JOIN merchants m ON t.merchant_id = m.id
WHERE i.user_id = $1 AND i.status IN ('PENDING', 'OVERDUE')
ORDER BY i.due_date ASC
`

type GetPendingInstallmentsWithDetailsRow struct {
	InstallmentID   pgtype.UUID        `json:"installment_id"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	InstallmentNum  int16              `json:"installment_num"`
	Amount          pgtype.Numeric     `json:"amount"`
	DueDate         pgtype.Date        `json:"due_date"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	Status          string             `json:"status"`
	ReactivationFee pgtype.Numeric     `json:"reactivation_fee"`
	DaysOverdue     int32              `json:"days_overdue"`
	TransactionID_2 pgtype.UUID        `json:"transaction_id_2"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	NumInstallments int16              `json:"num_installments"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
}

func (q *Queries) GetPendingInstallmentsWithDetails(ctx context.Context, userID pgtype.UUID) ([]GetPendingInstallmentsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getPendingInstallmentsWithDetails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingInstallmentsWithDetailsRow
	for rows.Next() {
		var i GetPendingInstallmentsWithDetailsRow
		if err := rows.Scan(
			&i.InstallmentID,
			&i.TransactionID,
			&i.UserID,
			&i.InstallmentNum,
			&i.Amount,
			&i.DueDate,
			&i.PaidAt,
			&i.Status,
			&i.ReactivationFee,
			&i.DaysOverdue,
			&i.TransactionID_2,
			&i.TotalAmount,
			&i.NumInstallments,
			&i.MerchantID,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaidInstallmentsWithDetails = `-- name: GetPaidInstallmentsWithDetails :many
SELECT
    i.id AS installment_id,
    i.transaction_id,
    i.user_id,
    i.installment_num,
    i.amount,
    i.due_date,
    i.paid_at,
    i.status,
    i.reactivation_fee,
    i.days_overdue,
    t.id AS transaction_id,
    t.total_amount,
    t.num_installments,
    t.merchant_id,
    m.trade_name AS merchant_name
FROM installments i
JOIN transactions t ON i.transaction_id = t.id
LEFT JOIN merchants m ON t.merchant_id = m.id
WHERE i.user_id = $1 AND i.status = 'PAID'
ORDER BY i.paid_at DESC
`

type GetPaidInstallmentsWithDetailsRow struct {
	InstallmentID   pgtype.UUID        `json:"installment_id"`
	TransactionID   pgtype.UUID        `json:"transaction_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	InstallmentNum  int16              `json:"installment_num"`
	Amount          pgtype.Numeric     `json:"amount"`
	DueDate         pgtype.Date        `json:"due_date"`
	PaidAt          pgtype.Timestamptz `json:"paid_at"`
	Status          string             `json:"status"`
	ReactivationFee pgtype.Numeric     `json:"reactivation_fee"`
	DaysOverdue     int32              `json:"days_overdue"`
	TransactionID_2 pgtype.UUID        `json:"transaction_id_2"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	NumInstallments int16              `json:"num_installments"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
}

func (q *Queries) GetPaidInstallmentsWithDetails(ctx context.Context, userID pgtype.UUID) ([]GetPaidInstallmentsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getPaidInstallmentsWithDetails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaidInstallmentsWithDetailsRow
	for rows.Next() {
		var i GetPaidInstallmentsWithDetailsRow
		if err := rows.Scan(
			&i.InstallmentID,
			&i.TransactionID,
			&i.UserID,
			&i.InstallmentNum,
			&i.Amount,
			&i.DueDate,
			&i.PaidAt,
			&i.Status,
			&i.ReactivationFee,
			&i.DaysOverdue,
			&i.TransactionID_2,
			&i.TotalAmount,
			&i.NumInstallments,
			&i.MerchantID,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionsByUser = `-- name: GetSubscriptionsByUser :many
SELECT
    s.id, s.user_id, s.merchant_id, s.credit_line_id, s.amount,
    s.product_name, s.status, s.next_billing_date, s.created_at, s.updated_at,
    m.trade_name AS merchant_name
FROM subscriptions s
LEFT JOIN merchants m ON s.merchant_id = m.id
WHERE s.user_id = $1
ORDER BY s.created_at DESC
`

type GetSubscriptionsByUserRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	MerchantID      pgtype.UUID        `json:"merchant_id"`
	CreditLineID    pgtype.UUID        `json:"credit_line_id"`
	Amount          pgtype.Numeric     `json:"amount"`
	ProductName     string             `json:"product_name"`
	Status          string             `json:"status"`
	NextBillingDate pgtype.Timestamptz `json:"next_billing_date"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	MerchantName    pgtype.Text        `json:"merchant_name"`
}

func (q *Queries) GetSubscriptionsByUser(ctx context.Context, userID pgtype.UUID) ([]GetSubscriptionsByUserRow, error) {
	rows, err := q.db.Query(ctx, getSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSubscriptionsByUserRow
	for rows.Next() {
		var i GetSubscriptionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.CreditLineID,
			&i.Amount,
			&i.ProductName,
			&i.Status,
			&i.NextBillingDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MerchantName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, merchant_id, credit_line_id, total_amount, down_payment, financed_amount, num_installments, status, qr_code_token, qr_expires_at, mdr_fee, description, created_at, updated_at FROM transactions WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id pgtype.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MerchantID,
		&i.CreditLineID,
		&i.TotalAmount,
		&i.DownPayment,
		&i.FinancedAmount,
		&i.NumInstallments,
		&i.Status,
		&i.QrCodeToken,
		&i.QrExpiresAt,
		&i.MdrFee,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTransactionsByUser = `-- name: GetTransactionsByUser :many
SELECT id, user_id, merchant_id, credit_line_id, total_amount, down_payment, financed_amount, num_installments, status, qr_code_token, qr_expires_at, mdr_fee, description, created_at, updated_at FROM transactions WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetTransactionsByUser(ctx context.Context, userID pgtype.UUID) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.MerchantID,
			&i.CreditLineID,
			&i.TotalAmount,
			&i.DownPayment,
			&i.FinancedAmount,
			&i.NumInstallments,
			&i.Status,
			&i.QrCodeToken,
			&i.QrExpiresAt,
			&i.MdrFee,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
