// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserPoints = `-- name: AddUserPoints :exec
UPDATE users
SET points = points + $2
WHERE id = $1
`

type AddUserPointsParams struct {
	ID     pgtype.UUID `json:"id"`
	Points int32       `json:"points"`
}

func (q *Queries) AddUserPoints(ctx context.Context, arg AddUserPointsParams) error {
	_, err := q.db.Exec(ctx, addUserPoints, arg.ID, arg.Points)
	return err
}

const checkAndLevelUpUser = `-- name: CheckAndLevelUpUser :exec
UPDATE users
SET level = level + 1
WHERE id = $1 AND points >= 100 AND level < 6
`

func (q *Queries) CheckAndLevelUpUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, checkAndLevelUpUser, id)
	return err
}

const processInstallmentPayment = `-- name: ProcessInstallmentPayment :one
UPDATE installments
SET
    status = 'PAID',
    paid_at = NOW()
WHERE id = $1
RETURNING id, transaction_id, user_id, installment_num, amount, due_date, paid_at, status, reactivation_fee, days_overdue, created_at, updated_at
`

func (q *Queries) ProcessInstallmentPayment(ctx context.Context, id pgtype.UUID) (Installment, error) {
	row := q.db.QueryRow(ctx, processInstallmentPayment, id)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.UserID,
		&i.InstallmentNum,
		&i.Amount,
		&i.DueDate,
		&i.PaidAt,
		&i.Status,
		&i.ReactivationFee,
		&i.DaysOverdue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
