// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddUserPoints(ctx context.Context, arg AddUserPointsParams) error
	ApplyReactivationFee(ctx context.Context, id pgtype.UUID) (Installment, error)
	CheckAndLevelUpUser(ctx context.Context, id pgtype.UUID) error
	CreateInstallment(ctx context.Context, arg CreateInstallmentParams) (Installment, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCreditLineByUser(ctx context.Context, arg GetCreditLineByUserParams) (CreditLine, error)
	GetMerchantPayouts(ctx context.Context) ([]GetMerchantPayoutsRow, error)
	GetOverdueInstallments(ctx context.Context) ([]Installment, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone string) (User, error)
	PauseUserCreditLines(ctx context.Context, userID pgtype.UUID) error
	ProcessInstallmentPayment(ctx context.Context, id pgtype.UUID) (Installment, error)
	TryScannerLock(ctx context.Context, key1 int32, key2 int32) (bool, error)
	UpdateCreditLineUsage(ctx context.Context, arg UpdateCreditLineUsageParams) (CreditLine, error)
	UpdateUserGamification(ctx context.Context, arg UpdateUserGamificationParams) (User, error)
}

var _ Querier = (*Queries)(nil)
