// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package database

import (
	"context"
)

const deleteExpiredQrTokens = `-- name: DeleteExpiredQrTokens :exec
DELETE FROM qr_tokens
WHERE status IN ('EXPIRED', 'CANCELLED')
  AND created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteExpiredQrTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredQrTokens)
	return err
}

const deleteRevokedConsents = `-- name: DeleteRevokedConsents :exec
DELETE FROM user_consents
WHERE granted = false
  AND revoked_at IS NOT NULL
  AND revoked_at < NOW() - INTERVAL '7 years'
`

func (q *Queries) DeleteRevokedConsents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteRevokedConsents)
	return err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :exec
DELETE FROM audit_log
WHERE created_at < NOW() - INTERVAL '7 years'
`

func (q *Queries) DeleteOldAuditLogs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldAuditLogs)
	return err
}
