// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scanner.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyReactivationFee = `-- name: ApplyReactivationFee :one
UPDATE installments
SET
    status = 'OVERDUE',
    reactivation_fee = 4.00,
    days_overdue = CURRENT_DATE - due_date
WHERE id = $1
RETURNING id, transaction_id, user_id, installment_num, amount, due_date, paid_at, status, reactivation_fee, days_overdue, created_at, updated_at
`

func (q *Queries) ApplyReactivationFee(ctx context.Context, id pgtype.UUID) (Installment, error) {
	row := q.db.QueryRow(ctx, applyReactivationFee, id)
	var i Installment
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.UserID,
		&i.InstallmentNum,
		&i.Amount,
		&i.DueDate,
		&i.PaidAt,
		&i.Status,
		&i.ReactivationFee,
		&i.DaysOverdue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOverdueInstallments = `-- name: GetOverdueInstallments :many
SELECT id, transaction_id, user_id, installment_num, amount, due_date, paid_at, status, reactivation_fee, days_overdue, created_at, updated_at FROM installments
WHERE status = 'PENDING' AND due_date < CURRENT_DATE - INTERVAL '2 days'
`

func (q *Queries) GetOverdueInstallments(ctx context.Context) ([]Installment, error) {
	rows, err := q.db.Query(ctx, getOverdueInstallments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Installment
	for rows.Next() {
		var i Installment
		if err := rows.Scan(
			&i.ID,
			&i.TransactionID,
			&i.UserID,
			&i.InstallmentNum,
			&i.Amount,
			&i.DueDate,
			&i.PaidAt,
			&i.Status,
			&i.ReactivationFee,
			&i.DaysOverdue,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingInstallmentsForReminder = `-- name: GetUpcomingInstallmentsForReminder :many
SELECT
    i.id,
    i.user_id,
    i.amount,
    i.due_date,
    i.installment_num,
    u.email,
    u.full_name
FROM installments i
JOIN users u ON i.user_id = u.id
WHERE i.status = 'PENDING'
  AND i.due_date >= CURRENT_DATE
  AND i.due_date <= CURRENT_DATE + INTERVAL '3 days'
  AND u.email IS NOT NULL
  AND u.is_active = true
`

type GetUpcomingInstallmentsForReminderRow struct {
	ID             pgtype.UUID    `json:"id"`
	UserID         pgtype.UUID    `json:"user_id"`
	Amount         pgtype.Numeric `json:"amount"`
	DueDate        pgtype.Date    `json:"due_date"`
	InstallmentNum int16          `json:"installment_num"`
	Email          pgtype.Text    `json:"email"`
	FullName       string         `json:"full_name"`
}

func (q *Queries) GetUpcomingInstallmentsForReminder(ctx context.Context) ([]GetUpcomingInstallmentsForReminderRow, error) {
	rows, err := q.db.Query(ctx, getUpcomingInstallmentsForReminder)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingInstallmentsForReminderRow
	for rows.Next() {
		var i GetUpcomingInstallmentsForReminderRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Amount,
			&i.DueDate,
			&i.InstallmentNum,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseUserCreditLines = `-- name: PauseUserCreditLines :exec
UPDATE credit_lines
SET
    status = 'PAUSED',
    paused_at = NOW()
WHERE user_id = $1 AND type != 'SALUD_COTIDIANA'
`

func (q *Queries) PauseUserCreditLines(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, pauseUserCreditLines, userID)
	return err
}

const tryScannerLock = `-- name: TryScannerLock :one
SELECT pg_try_advisory_xact_lock($1, $2) AS acquired
`

type TryScannerLockParams struct {
	PgTryAdvisoryXactLock   int32 `json:"pg_try_advisory_xact_lock"`
	PgTryAdvisoryXactLock_2 int32 `json:"pg_try_advisory_xact_lock_2"`
}

func (q *Queries) TryScannerLock(ctx context.Context, arg TryScannerLockParams) (bool, error) {
	row := q.db.QueryRow(ctx, tryScannerLock, arg.PgTryAdvisoryXactLock, arg.PgTryAdvisoryXactLock_2)
	var acquired bool
	err := row.Scan(&acquired)
	return acquired, err
}
