// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: triage.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTriage = `-- name: CreateTriage :one
INSERT INTO triage (user_id, symptoms, perceived_severity, priority, status)
VALUES ($1, $2, $3, $4, 'PENDING')
RETURNING id, user_id, symptoms, perceived_severity, priority, status, recommendation, created_at, updated_at
`

type CreateTriageParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	Symptoms          string      `json:"symptoms"`
	PerceivedSeverity int16       `json:"perceived_severity"`
	Priority          string      `json:"priority"`
}

func (q *Queries) CreateTriage(ctx context.Context, arg CreateTriageParams) (Triage, error) {
	row := q.db.QueryRow(ctx, createTriage,
		arg.UserID,
		arg.Symptoms,
		arg.PerceivedSeverity,
		arg.Priority,
	)
	var i Triage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symptoms,
		&i.PerceivedSeverity,
		&i.Priority,
		&i.Status,
		&i.Recommendation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTriageByID = `-- name: GetTriageByID :one
SELECT id, user_id, symptoms, perceived_severity, priority, status, recommendation, created_at, updated_at FROM triage WHERE id = $1
`

func (q *Queries) GetTriageByID(ctx context.Context, id pgtype.UUID) (Triage, error) {
	row := q.db.QueryRow(ctx, getTriageByID, id)
	var i Triage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Symptoms,
		&i.PerceivedSeverity,
		&i.Priority,
		&i.Status,
		&i.Recommendation,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTriageByUser = `-- name: GetTriageByUser :many
SELECT id, user_id, symptoms, perceived_severity, priority, status, recommendation, created_at, updated_at FROM triage WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetTriageByUser(ctx context.Context, userID pgtype.UUID) ([]Triage, error) {
	rows, err := q.db.Query(ctx, getTriageByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Triage
	for rows.Next() {
		var i Triage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Symptoms,
			&i.PerceivedSeverity,
			&i.Priority,
			&i.Status,
			&i.Recommendation,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
