// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    phone, email, password_hash, full_name, national_id, role
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, phone, email, password_hash, full_name, national_id, role, level, points, total_paid, installments_paid_count, is_active, created_at, updated_at, is_phone_verified, is_credit_frozen_for_electives, is_email_verified, profile_photo_url
`

type CreateUserParams struct {
	Phone        string      `json:"phone"`
	Email        pgtype.Text `json:"email"`
	PasswordHash string      `json:"password_hash"`
	FullName     string      `json:"full_name"`
	NationalID   pgtype.Text `json:"national_id"`
	Role         string      `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.NationalID,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.NationalID,
		&i.Role,
		&i.Level,
		&i.Points,
		&i.TotalPaid,
		&i.InstallmentsPaidCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPhoneVerified,
		&i.IsCreditFrozenForElectives,
		&i.IsEmailVerified,
		&i.ProfilePhotoUrl,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, phone, email, password_hash, full_name, national_id, role, level, points, total_paid, installments_paid_count, is_active, created_at, updated_at, is_phone_verified, is_credit_frozen_for_electives, is_email_verified, profile_photo_url FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.NationalID,
		&i.Role,
		&i.Level,
		&i.Points,
		&i.TotalPaid,
		&i.InstallmentsPaidCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPhoneVerified,
		&i.IsCreditFrozenForElectives,
		&i.IsEmailVerified,
		&i.ProfilePhotoUrl,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone, email, password_hash, full_name, national_id, role, level, points, total_paid, installments_paid_count, is_active, created_at, updated_at, is_phone_verified, is_credit_frozen_for_electives, is_email_verified, profile_photo_url FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.NationalID,
		&i.Role,
		&i.Level,
		&i.Points,
		&i.TotalPaid,
		&i.InstallmentsPaidCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPhoneVerified,
		&i.IsCreditFrozenForElectives,
		&i.IsEmailVerified,
		&i.ProfilePhotoUrl,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, email, password_hash, full_name, national_id, role, level, points, total_paid, installments_paid_count, is_active, created_at, updated_at, is_phone_verified, is_credit_frozen_for_electives, is_email_verified, profile_photo_url FROM users WHERE phone = $1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.NationalID,
		&i.Role,
		&i.Level,
		&i.Points,
		&i.TotalPaid,
		&i.InstallmentsPaidCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPhoneVerified,
		&i.IsCreditFrozenForElectives,
		&i.IsEmailVerified,
		&i.ProfilePhotoUrl,
	)
	return i, err
}

const incrementUserTotalPaid = `-- name: IncrementUserTotalPaid :exec
UPDATE users
SET
    total_paid = total_paid + $2,
    installments_paid_count = installments_paid_count + 1
WHERE id = $1
`

type IncrementUserTotalPaidParams struct {
	ID        pgtype.UUID    `json:"id"`
	TotalPaid pgtype.Numeric `json:"total_paid"`
}

func (q *Queries) IncrementUserTotalPaid(ctx context.Context, arg IncrementUserTotalPaidParams) error {
	_, err := q.db.Exec(ctx, incrementUserTotalPaid, arg.ID, arg.TotalPaid)
	return err
}

const updateUserGamification = `-- name: UpdateUserGamification :one
UPDATE users
SET
    points = points + $2,
    level = $3,
    total_paid = total_paid + $4,
    installments_paid_count = installments_paid_count + $5
WHERE id = $1
RETURNING id, phone, email, password_hash, full_name, national_id, role, level, points, total_paid, installments_paid_count, is_active, created_at, updated_at, is_phone_verified, is_credit_frozen_for_electives, is_email_verified, profile_photo_url
`

type UpdateUserGamificationParams struct {
	ID                    pgtype.UUID    `json:"id"`
	Points                int32          `json:"points"`
	Level                 int16          `json:"level"`
	TotalPaid             pgtype.Numeric `json:"total_paid"`
	InstallmentsPaidCount int32          `json:"installments_paid_count"`
}

func (q *Queries) UpdateUserGamification(ctx context.Context, arg UpdateUserGamificationParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserGamification,
		arg.ID,
		arg.Points,
		arg.Level,
		arg.TotalPaid,
		arg.InstallmentsPaidCount,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.NationalID,
		&i.Role,
		&i.Level,
		&i.Points,
		&i.TotalPaid,
		&i.InstallmentsPaidCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPhoneVerified,
		&i.IsCreditFrozenForElectives,
		&i.IsEmailVerified,
		&i.ProfilePhotoUrl,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash string      `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfilePhoto = `-- name: UpdateUserProfilePhoto :one
UPDATE users
SET profile_photo_url = $2
WHERE id = $1
RETURNING id, phone, email, password_hash, full_name, national_id, role, level, points, total_paid, installments_paid_count, is_active, created_at, updated_at, is_phone_verified, is_credit_frozen_for_electives, is_email_verified, profile_photo_url
`

type UpdateUserProfilePhotoParams struct {
	ID              pgtype.UUID `json:"id"`
	ProfilePhotoUrl pgtype.Text `json:"profile_photo_url"`
}

func (q *Queries) UpdateUserProfilePhoto(ctx context.Context, arg UpdateUserProfilePhotoParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfilePhoto, arg.ID, arg.ProfilePhotoUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.NationalID,
		&i.Role,
		&i.Level,
		&i.Points,
		&i.TotalPaid,
		&i.InstallmentsPaidCount,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsPhoneVerified,
		&i.IsCreditFrozenForElectives,
		&i.IsEmailVerified,
		&i.ProfilePhotoUrl,
	)
	return i, err
}

const verifyEmail = `-- name: VerifyEmail :exec
UPDATE users
SET
    is_email_verified = TRUE,
    kyc_status = 'APPROVED'
WHERE id = $1
`

func (q *Queries) VerifyEmail(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, verifyEmail, id)
	return err
}
